<?php

namespace Database\Seeders;

use App\Models\Condition;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AnxietyDisordersGeneralizedAnxietyDisorderPanicDisorderConditionSeeder extends Seeder
{
    public function run(): void
    {
        Condition::updateOrCreate(
            ['slug' => Str::slug('Anxiety Disorders (Generalized Anxiety Disorder, Panic Disorder)')],
            [
                'name' => 'Anxiety Disorders (Generalized Anxiety Disorder, Panic Disorder)',
                'slug' => Str::slug('Anxiety Disorders (Generalized Anxiety Disorder, Panic Disorder)'),
                'h1' => 'Anxiety Disorders (Generalized Anxiety Disorder, Panic Disorder)',
                'icon' => null,
                'cta_text' => null,
                'cta_link' => null,
                'about' => 'Anxiety disorders are mental health conditions characterized by excessive fear, worry, nervousness, or panic that interfere with daily activities, emotional well-being, and physical health. Generalized Anxiety Disorder (GAD) involves persistent and excessive worry about everyday situations, while Panic Disorder is characterized by sudden and intense panic attacks accompanied by physical and emotional symptoms. Anxiety disorders can affect concentration, sleep, relationships, work performance, and overall quality of life.',
                'about_more' => 'Bipolar disorder is a mental health condition characterized by significant shifts in mood, energy levels, activity, and behavior. Individuals with bipolar disorder experience episodes of emotional highs, known as mania or hypomania, and periods of depression that can affect daily functioning, relationships, sleep, concentration, and decision-making. The intensity and duration of mood changes may vary from person to person. Schizophrenia and other psychotic disorders are serious mental health conditions that affect a person’s thinking, emotions, perception, and behavior. These disorders may cause individuals to lose touch with reality, leading to difficulties in understanding what is real and what is not. Symptoms can interfere with communication, relationships, work, and daily functioning, often requiring long-term psychiatric care and support. Obsessive Compulsive Disorder (OCD) is a mental health condition characterized by recurring unwanted thoughts, fears, or urges known as obsessions, along with repetitive behaviors or mental rituals called compulsions. Individuals with OCD often perform these repetitive actions to reduce anxiety or prevent feared situations, even when they recognize the thoughts or behaviors may be excessive. The condition can interfere with daily activities, relationships, work, and emotional well-being. Post Traumatic Stress Disorder (PTSD) is a mental health condition that can develop after experiencing or witnessing a traumatic, frightening, or life-threatening event. These events may include accidents, violence, abuse, natural disasters, combat situations, or other emotionally distressing experiences. PTSD can affect a person’s emotions, thoughts, sleep, behavior, and ability to cope with daily life, sometimes lasting for months or years if untreated. Attention Deficit Hyperactivity Disorder (ADHD) is a neurodevelopmental condition that affects attention, impulse control, behavior, and activity levels. Individuals with ADHD may experience difficulty focusing, staying organized, completing tasks, or controlling impulsive actions. Although commonly diagnosed during childhood, ADHD can continue into adolescence and adulthood, affecting academic performance, relationships, work, and daily functioning. Autism Spectrum Disorder (ASD) is a neurodevelopmental condition that affects communication, social interaction, behavior, and learning patterns. Individuals with autism may experience differences in how they understand emotions, respond to social situations, process sensory information, and express themselves. The condition varies widely from person to person, with some individuals requiring minimal support while others may need ongoing developmental and behavioral assistance.',
                'overview' => 'Anxiety disorders are mental health conditions characterized by excessive fear, worry, nervousness, or panic that interfere with daily activities, emotional well-being, and physical health. Generalized Anxiety Disorder (GAD) involves persistent and excessive worry about everyday situations, while Panic Disorder is characterized by sudden and intense panic attacks accompanied by physical and emotional symptoms. Anxiety disorders can affect concentration, sleep, relationships, work performance, and overall quality of life. Bipolar disorder is a mental health condition characterized by significant shifts in mood, energy levels, activity, and behavior. Individuals with bipolar disorder experience episodes of emotional highs, known as mania or hypomania, and periods of depression that can affect daily functioning, relationships, sleep, concentration, and decision-making. The intensity and duration of mood changes may vary from person to person. Schizophrenia and other psychotic disorders are serious mental health conditions that affect a person’s thinking, emotions, perception, and behavior. These disorders may cause individuals to lose touch with reality, leading to difficulties in understanding what is real and what is not. Symptoms can interfere with communication, relationships, work, and daily functioning, often requiring long-term psychiatric care and support. Obsessive Compulsive Disorder (OCD) is a mental health condition characterized by recurring unwanted thoughts, fears, or urges known as obsessions, along with repetitive behaviors or mental rituals called compulsions. Individuals with OCD often perform these repetitive actions to reduce anxiety or prevent feared situations, even when they recognize the thoughts or behaviors may be excessive. The condition can interfere with daily activities, relationships, work, and emotional well-being. Post Traumatic Stress Disorder (PTSD) is a mental health condition that can develop after experiencing or witnessing a traumatic, frightening, or life-threatening event. These events may include accidents, violence, abuse, natural disasters, combat situations, or other emotionally distressing experiences. PTSD can affect a person’s emotions, thoughts, sleep, behavior, and ability to cope with daily life, sometimes lasting for months or years if untreated. Attention Deficit Hyperactivity Disorder (ADHD) is a neurodevelopmental condition that affects attention, impulse control, behavior, and activity levels. Individuals with ADHD may experience difficulty focusing, staying organized, completing tasks, or controlling impulsive actions. Although commonly diagnosed during childhood, ADHD can continue into adolescence and adulthood, affecting academic performance, relationships, work, and daily functioning. Autism Spectrum Disorder (ASD) is a neurodevelopmental condition that affects communication, social interaction, behavior, and learning patterns. Individuals with autism may experience differences in how they understand emotions, respond to social situations, process sensory information, and express themselves. The condition varies widely from person to person, with some individuals requiring minimal support while others may need ongoing developmental and behavioral assistance.',
                'symptoms' => [
            ['value' => 'Excessive worry, nervousness, or constant fear'],
            ['value' => 'Restlessness, irritability, or feeling on edge'],
            ['value' => 'Rapid heartbeat, sweating, trembling, or shortness of breath'],
            ['value' => 'Panic attacks with sudden intense fear or chest discomfort'],
            ['value' => 'Difficulty sleeping, concentrating, or relaxing'],
            ['value' => 'Common Causes'],
            ['value' => 'Chemical imbalances affecting brain function and stress response'],
            ['value' => 'Genetic and family history of anxiety disorders'],
            ['value' => 'Chronic stress, trauma, or emotional difficulties'],
            ['value' => 'Chronic illness, pain disorders, or autoimmune conditions'],
            ['value' => 'Substance use, hormonal changes, or major life events'],
            ['value' => 'Extreme mood swings between emotional highs and lows'],
            ['value' => 'Increased energy, excitement, or unusually elevated mood during manic episodes'],
            ['value' => 'Persistent sadness, hopelessness, or loss of interest during depressive episodes'],
            ['value' => 'Changes in sleep patterns, appetite, or activity levels'],
            ['value' => 'Difficulty concentrating, impulsive behavior, or poor decision-making'],
            ['value' => 'Hallucinations such as hearing or seeing things that are not present'],
            ['value' => 'Delusions or strongly held false beliefs'],
            ['value' => 'Disorganized thinking or confused speech patterns'],
            ['value' => 'Social withdrawal and reduced emotional expression'],
            ['value' => 'Difficulty concentrating, thinking clearly, or performing daily activities'],
            ['value' => 'Fear of contamination, germs, or dirt'],
            ['value' => 'Repeated checking behaviors due to doubt or uncertainty'],
            ['value' => 'Strong need for order, symmetry, or perfection'],
            ['value' => 'Intrusive thoughts related to harm, aggression, or loss of control'],
            ['value' => 'Repetitive rituals such as cleaning, counting, arranging, or hand washing'],
            ['value' => 'Recurrent distressing memories or flashbacks of the traumatic event'],
            ['value' => 'Nightmares or difficulty sleeping'],
            ['value' => 'Anxiety, fear, or feeling constantly alert or on edge'],
            ['value' => 'Avoidance of places, people, or situations linked to the trauma'],
            ['value' => 'Mood changes such as sadness, anger, guilt, or emotional numbness'],
            ['value' => 'Frequently forgetting tasks or responsibilities'],
            ['value' => 'Difficulty organizing activities, schoolwork, or daily routines'],
            ['value' => 'Frequently losing personal belongings or important items'],
            ['value' => 'Trouble staying focused during conversations, reading, or tasks'],
            ['value' => 'Easily distracted or appearing inattentive during activities'],
            ['value' => 'Limited eye contact or reduced facial expressions during interaction'],
            ['value' => 'Delayed speech development or difficulty with communication'],
            ['value' => 'Trouble understanding social cues, instructions, or conversations'],
            ['value' => 'Repetitive behaviors, routines, or focused interests'],
            ['value' => 'Difficulty interacting socially or responding appropriately in group settings'],
        ],
                'causes' => [
            ['value' => 'Family history of bipolar disorder or mental health conditions'],
            ['value' => 'Imbalance of brain chemicals affecting mood regulation'],
            ['value' => 'Stressful life events or emotional trauma'],
            ['value' => 'Sleep disturbances or major lifestyle changes'],
            ['value' => 'Substance misuse or certain medical conditions'],
            ['value' => 'Family history of schizophrenia or psychotic disorders'],
            ['value' => 'Imbalance of brain chemicals affecting mental function'],
            ['value' => 'Severe emotional stress or traumatic experiences'],
            ['value' => 'Substance misuse or drug-induced psychosis'],
            ['value' => 'Complications during brain development or neurological disorders'],
            ['value' => 'Family history of OCD or anxiety disorders'],
            ['value' => 'Imbalance of brain chemicals affecting thought processing'],
            ['value' => 'Stressful life events or emotional trauma'],
            ['value' => 'Personality traits involving perfectionism or high anxiety'],
            ['value' => 'Certain neurological or mental health conditions'],
            ['value' => 'Exposure to traumatic or life-threatening events'],
            ['value' => 'Physical, emotional, or sexual abuse'],
            ['value' => 'Serious accidents, violence, or natural disasters'],
            ['value' => 'Military combat or witnessing traumatic incidents'],
            ['value' => 'Lack of emotional support after a traumatic experience'],
            ['value' => 'Family history of ADHD or other mental health conditions'],
            ['value' => 'Exposure to environmental toxins such as lead during childhood'],
            ['value' => 'Alcohol, tobacco, or substance exposure during pregnancy'],
            ['value' => 'Premature birth or low birth weight'],
            ['value' => 'Differences in brain development and neurotransmitter function'],
            ['value' => 'Family history or genetic factors affecting brain development'],
            ['value' => 'Pregnancy-related complications or premature birth'],
            ['value' => 'Exposure to certain medications or environmental factors during pregnancy'],
            ['value' => 'Reduced oxygen supply during pregnancy or delivery'],
            ['value' => 'Differences in neurological development and brain function'],
        ],
                'risks' => [
            ['value' => 'Sleep disturbances and chronic fatigue'],
            ['value' => 'Reduced work, academic, or social functioning'],
            ['value' => 'Increased risk of depression or substance misuse'],
            ['value' => 'Panic-related avoidance behaviors and social withdrawal'],
            ['value' => 'Worsening physical health due to prolonged stress and anxiety'],
            ['value' => 'Relationship difficulties and social withdrawal'],
            ['value' => 'Poor academic or work performance'],
            ['value' => 'Substance abuse and unhealthy coping behaviors'],
            ['value' => 'Increased risk of anxiety, depression, or self-harm'],
            ['value' => 'Financial, legal, or behavioral problems during manic episodes'],
            ['value' => 'Difficulty maintaining relationships and social interaction'],
            ['value' => 'Reduced work, academic, or daily life functioning'],
            ['value' => 'Increased risk of anxiety, depression, or substance abuse'],
            ['value' => 'Self-harm behavior or suicidal thoughts in severe cases'],
            ['value' => 'Poor self-care and long-term emotional distress'],
            ['value' => 'Difficulty completing daily tasks and responsibilities'],
            ['value' => 'Increased anxiety, stress, and emotional exhaustion'],
            ['value' => 'Social withdrawal and relationship difficulties'],
            ['value' => 'Depression or other associated mental health conditions'],
            ['value' => 'Reduced quality of life due to time-consuming compulsive behaviors'],
            ['value' => 'Chronic anxiety, depression, or panic disorders'],
            ['value' => 'Social withdrawal and relationship difficulties'],
            ['value' => 'Sleep disturbances and emotional instability'],
            ['value' => 'Substance misuse or unhealthy coping behaviors'],
            ['value' => 'Difficulty functioning at work, school, or daily activities'],
            ['value' => 'Poor academic or work performance'],
            ['value' => 'Difficulty maintaining social relationships and communication'],
            ['value' => 'Increased risk of accidents and impulsive behavior'],
            ['value' => 'Low self-esteem and emotional difficulties'],
            ['value' => 'Higher risk of anxiety, depression, or substance misuse later in life'],
            ['value' => 'Difficulty with communication and social relationships'],
            ['value' => 'Delayed learning, speech, or developmental milestones'],
            ['value' => 'Emotional or behavioral challenges in daily activities'],
            ['value' => 'Anxiety, attention difficulties, or sensory sensitivities'],
            ['value' => 'Reduced independence without early intervention and support'],
        ],
                'diagnosis' => [],
                'treatment' => [
            ['value' => 'Treatment for anxiety disorders usually involves a combination of psychological therapy, lifestyle modification, stress management, and medications depending on the severity of symptoms. Common treatments include cognitive behavioral therapy (CBT), relaxation techniques, mindfulness practices, antidepressant or anti-anxiety medications, breathing exercises, sleep management strategies, and supportive counseling. Regular exercise, healthy routines, emotional support, and long-term mental health follow-up also play an important role in improving symptom control and emotional well-being.'],
            ['value' => 'Regular mental health evaluation and follow-up care'],
            ['value' => 'Monitoring response to therapy and medications'],
            ['value' => 'Stress management and relaxation training programs'],
            ['value' => 'Encouragement of healthy sleep, exercise, and lifestyle habits'],
            ['value' => 'Long-term counseling and emotional wellness support when required'],
            ['value' => 'Mood-stabilizing medications and psychiatric care'],
            ['value' => 'Cognitive Behavioral Therapy (CBT) and psychotherapy'],
            ['value' => 'Stress management and lifestyle modifications'],
            ['value' => 'Sleep regulation and healthy daily routines'],
            ['value' => 'Emotional support, counseling, and long-term mental health follow-up'],
            ['value' => 'Antipsychotic medications prescribed by mental health specialists'],
            ['value' => 'Psychological counseling and supportive psychotherapy'],
            ['value' => 'Cognitive Behavioral Therapy (CBT) and rehabilitation programs'],
            ['value' => 'Family support, social skills training, and community care'],
            ['value' => 'Long-term psychiatric monitoring and lifestyle management'],
            ['value' => 'Cognitive Behavioral Therapy (CBT), especially Exposure and Response Prevention (ERP)'],
            ['value' => 'Medications such as antidepressants prescribed by mental health specialists'],
            ['value' => 'Stress management and relaxation techniques'],
            ['value' => 'Counseling, emotional support, and behavioral therapy'],
            ['value' => 'Regular psychiatric follow-up and long-term mental health care'],
            ['value' => 'Trauma-focused psychotherapy and counseling'],
            ['value' => 'Cognitive Behavioral Therapy (CBT) and supportive therapy'],
            ['value' => 'Medications to manage anxiety, depression, or sleep disturbances'],
            ['value' => 'Stress management, relaxation techniques, and emotional support programs'],
            ['value' => 'Long-term mental health follow-up and rehabilitation support'],
            ['value' => 'Stimulant and non-stimulant medications prescribed by specialists'],
            ['value' => 'Behavioral therapy and Cognitive Behavioral Therapy (CBT)'],
            ['value' => 'Counseling and emotional support programs'],
            ['value' => 'Structured routines, organizational training, and lifestyle management'],
            ['value' => 'Parent guidance, educational support, and long-term follow-up care'],
            ['value' => 'Behavioral therapy and developmental intervention programs'],
            ['value' => 'Speech and language therapy'],
            ['value' => 'Occupational therapy and social skills training'],
            ['value' => 'Educational support and individualized learning plans'],
            ['value' => 'Family counseling, emotional support, and long-term developmental care'],
        ],
                'recovery' => 'The long-term outlook for anxiety disorders is generally positive with early diagnosis, proper treatment, emotional support, and consistent mental healthcare. Therapy, medication adherence when prescribed, stress reduction, healthy lifestyle habits, social support, and regular follow-up significantly help reduce anxiety symptoms, improve emotional resilience, enhance daily functioning, and support long-term mental well-being. ___________________ 3. Bipolar Disorder Bipolar Disorder Bipolar disorder can be effectively managed with early diagnosis, proper treatment, and continuous mental health support. Many individuals lead stable and productive lives through medication management, therapy, healthy lifestyle habits, and regular follow-up care. Long-term treatment and emotional support are important for reducing mood episodes and improving overall quality of life. _____________ 4. Schizophrenia & Other Psychotic Disorders Recovery from schizophrenia and other psychotic disorders varies depending on the severity of symptoms, early diagnosis, and response to treatment. Many individuals experience improvement with medications, therapy, rehabilitation, and continuous mental health support. Long-term care, emotional support, and regular psychiatric follow-up can help improve stability, independence, and overall quality of life. ______________ 5. Obsessive-Compulsive Disorder (OCD) Obsessive Compulsive Disorder (OCD) Recovery from Obsessive Compulsive Disorder is possible with early diagnosis, proper treatment, and continuous support. Many individuals experience significant improvement through therapy, medications, and healthy coping strategies. Long-term management and consistent mental health care can help reduce obsessive thoughts, control compulsive behaviors, and improve overall emotional well-being and daily functioning. ____________ 6. Post-Traumatic Stress Disorder (PTSD) Post Traumatic Stress Disorder (PTSD) Recovery from PTSD is possible with proper mental health care, emotional support, and early treatment. Many individuals improve significantly through therapy, medications, coping strategies, and supportive relationships. Long-term recovery focuses on reducing emotional distress, improving daily functioning, and helping individuals regain confidence, stability, and overall quality of life. ____________ 7. Attention Deficit Hyperactivity Disorder (ADHD) Attention Deficit Hyperactivity Disorder (ADHD) ADHD can be effectively managed with early diagnosis, appropriate treatment, and continuous support. Many individuals improve significantly through therapy, medications, structured routines, and educational assistance. Long-term management and supportive care can help improve concentration, emotional regulation, academic performance, social interaction, and overall quality of life. ______________ 8. Autism Spectrum Disorders Autism Spectrum Disorder (ASD) Autism Spectrum Disorder is a lifelong condition, but early diagnosis and supportive therapies can significantly improve communication, social interaction, learning abilities, and independence. Many individuals with ASD benefit from structured routines, educational support, therapy programs, and family involvement. Long-term care and personalized interventions help improve quality of life and overall developmental progress. _____________ 9. Eating Disorders (Anorexia, Bulimia, Binge Eating)',
                'sort_order' => 1,
                'is_active' => true,
                'meta_title' => 'Anxiety Disorders (Generalized Anxiety Disorder, Panic Disorder)',
                'meta_description' => 'Anxiety disorders are mental health conditions characterized by excessive fear, worry, nervousness, or panic that interfere with daily activities, emotional wel',
                'meta_keywords' => '',
            ]
        );
    }
}
