<?php

namespace Database\Seeders;

use App\Models\Procedure;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BrainstemEvokedResponseAudiometryBERASeeder extends Seeder
{
    public function run(): void
    {
        $procedure = Procedure::updateOrCreate(
            ['slug' => Str::slug('Brainstem Evoked Response Audiometry (BERA)')],
            [
                'title' => 'Brainstem Evoked Response Audiometry (BERA)',
                'slug' => Str::slug('Brainstem Evoked Response Audiometry (BERA)'),
                'introduction' => 'Brainstem Evoked Response Audiometry (BERA) is an advanced hearing assessment test used to evaluate the hearing nerve and brainstem response to sound stimulation. The test is especially useful in infants, young children, uncooperative patients, and individuals suspected of neurological hearing disorders. BERA helps detect hearing impairment and assess auditory pathway function accurately.',
                'what_is' => 'During the test, small electrodes are placed on the scalp and ears while sound signals are delivered through earphones. The equipment records electrical responses generated by the auditory nerve and brainstem. BERA is commonly used for: Newborn hearing assessment Pediatric hearing evaluation Neurological hearing disorders Unexplained hearing loss Pre-cochlear implant evaluation The procedure is painless and may be performed during natural sleep or mild sedation in children.',
                'symptoms' => [
            ['value' => 'Delayed speech development'],
            ['value' => 'Poor response to sounds'],
            ['value' => 'Suspected hearing loss'],
            ['value' => 'Neurological hearing abnormalities'],
            ['value' => 'Difficulty understanding speech'],
        ],
                'causes' => [],
                'condition_risks' => [
            ['value' => 'Mild skin irritation from electrodes'],
            ['value' => 'Temporary discomfort during electrode placement'],
            ['value' => 'Need for sedation in some children'],
            ['value' => 'Inaccurate results due to patient movement'],
            ['value' => 'Rare anxiety during testing'],
        ],
                'preventions' => [],
                'diagnosis_tests' => [],
                'treatment_overview' => '',
                'surgery_types' => [],
                'recovery_timeline' => [],
                'post_op_care' => [
            ['value' => 'Continue hearing follow-up evaluations regularly'],
            ['value' => 'Monitor speech and language development'],
            ['value' => 'Follow rehabilitation recommendations carefully'],
            ['value' => 'Attend ENT and audiology consultations'],
            ['value' => 'Seek early intervention if hearing loss is confirmed'],
        ],
                'surgery_risks' => [
            ['value' => 'Mild skin irritation from electrodes'],
            ['value' => 'Temporary discomfort during electrode placement'],
            ['value' => 'Need for sedation in some children'],
            ['value' => 'Inaccurate results due to patient movement'],
            ['value' => 'Rare anxiety during testing'],
        ],
                'long_term_outlook' => 'BERA supports early diagnosis of hearing and neurological auditory disorders, allowing timely treatment and improved long-term communication outcomes.',
                'conclusion' => '',
                'seo_title' => 'Brainstem Evoked Response Audiometry (BERA)',
                'seo_description' => 'Brainstem Evoked Response Audiometry (BERA) is an advanced hearing assessment test used to evaluate the hearing nerve and brainstem response to sound stimulation. The test is especially useful in infants, young children, uncooperative patients, and individuals suspected of neurological hearing disorders. BERA helps detect hearing impairment and assess auditory pathway function accurately.',
                'seo_keywords' => '',
                'is_active' => true,
            ]
        );
    }
}
