<?php

namespace Database\Seeders;

use App\Models\Procedure;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EEGVideoEEGSeeder extends Seeder
{
    public function run(): void
    {
        $procedure = Procedure::updateOrCreate(
            ['slug' => Str::slug('EEG / Video EEG')],
            [
                'title' => 'EEG / Video EEG',
                'slug' => Str::slug('EEG / Video EEG'),
                'introduction' => 'Electroencephalography (EEG) and Video EEG are specialized neurodiagnostic procedures used to record and evaluate the electrical activity of the brain. These tests help diagnose and monitor neurological conditions such as epilepsy, seizures, sleep disorders, altered consciousness, and other brain-related abnormalities. Video EEG combines continuous EEG monitoring with synchronized video recording to correlate brain activity with physical symptoms or behavioral events.',
                'what_is' => 'EEG involves placing small electrodes on the scalp to detect and record electrical signals generated by brain activity. The procedure is painless, non-invasive, and commonly performed in neurology departments, epilepsy monitoring units, and diagnostic centers. Video EEG provides extended monitoring with simultaneous video observation, allowing neurologists to analyze seizure activity, abnormal movements, behavioral changes, and neurological episodes more accurately. These procedures play an important role in diagnosing seizure disorders, monitoring treatment response, and planning long-term neurological care.',
                'symptoms' => [
            ['value' => 'Seizures or unexplained loss of consciousness'],
            ['value' => 'Recurrent fainting spells or blackouts'],
            ['value' => 'Abnormal movements, twitching, or muscle jerking episodes'],
            ['value' => 'Sleep disturbances or unusual nighttime behaviors'],
            ['value' => 'Memory problems, confusion, or altered mental status'],
        ],
                'causes' => [
            ['value' => 'Epilepsy and seizure disorders'],
            ['value' => 'Brain injuries, infections, or neurological diseases'],
            ['value' => 'Sleep disorders and abnormal brain activity during sleep'],
            ['value' => 'Stroke, tumors, or structural brain abnormalities'],
            ['value' => 'Metabolic, inflammatory, or neurodevelopmental conditions affecting brain function'],
        ],
                'condition_risks' => [
            ['value' => 'Mild skin irritation from electrode placement'],
            ['value' => 'Temporary discomfort during prolonged monitoring sessions'],
            ['value' => 'Rare triggering of seizures during activation procedures'],
            ['value' => 'Sleep deprivation-related fatigue if required before testing'],
            ['value' => 'Need for extended monitoring in complex neurological cases'],
            ['value' => 'Treatment Options'],
            ['value' => 'EEG and Video EEG help neurologists diagnose neurological conditions accurately and guide individualized treatment planning. Based on the findings, treatment may include anti-seizure medications, sleep disorder management, neurological rehabilitation, lifestyle modification, surgical evaluation for epilepsy, behavioral therapy, and long-term neurological follow-up. Continuous EEG monitoring may also assist in adjusting medications, identifying seizure triggers, and improving long-term seizure control and neurological outcomes.'],
        ],
                'preventions' => [],
                'diagnosis_tests' => [],
                'treatment_overview' => '',
                'surgery_types' => [],
                'recovery_timeline' => [],
                'post_op_care' => [
            ['value' => 'Resume normal activities unless otherwise advised by the physician'],
            ['value' => 'Follow medication and neurological treatment recommendations'],
            ['value' => 'Attend follow-up consultations for interpretation of EEG findings'],
            ['value' => 'Continue seizure precautions or safety measures if prescribed'],
            ['value' => 'Undergo additional neurological evaluation or imaging if required'],
        ],
                'surgery_risks' => [
            ['value' => 'Mild skin irritation from electrode placement'],
            ['value' => 'Temporary discomfort during prolonged monitoring sessions'],
            ['value' => 'Rare triggering of seizures during activation procedures'],
            ['value' => 'Sleep deprivation-related fatigue if required before testing'],
            ['value' => 'Need for extended monitoring in complex neurological cases'],
            ['value' => 'Treatment Options'],
            ['value' => 'EEG and Video EEG help neurologists diagnose neurological conditions accurately and guide individualized treatment planning. Based on the findings, treatment may include anti-seizure medications, sleep disorder management, neurological rehabilitation, lifestyle modification, surgical evaluation for epilepsy, behavioral therapy, and long-term neurological follow-up. Continuous EEG monitoring may also assist in adjusting medications, identifying seizure triggers, and improving long-term seizure control and neurological outcomes.'],
        ],
                'long_term_outlook' => 'EEG and Video EEG play a vital role in the early diagnosis, monitoring, and management of neurological disorders, especially epilepsy and seizure-related conditions. Advancements in digital neurodiagnostic technology, prolonged monitoring systems, and AI-assisted brain activity analysis continue to improve diagnostic accuracy, treatment planning, seizure management, and long-term neurological care outcomes.',
                'conclusion' => '',
                'seo_title' => 'EEG / Video EEG',
                'seo_description' => 'Electroencephalography (EEG) and Video EEG are specialized neurodiagnostic procedures used to record and evaluate the electrical activity of the brain. These tests help diagnose and monitor neurological conditions such as epilepsy, seizures, sleep disorders, altered consciousness, and other brain-related abnormalities. Video EEG combines continuous EEG monitoring with synchronized video recording to correlate brain activity with physical symptoms or behavioral events.',
                'seo_keywords' => '',
                'is_active' => true,
            ]
        );
    }
}
