<?php

namespace Database\Seeders;

use App\Models\Procedure;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ElectrocauteryRadiofrequencyDevicesSeeder extends Seeder
{
    public function run(): void
    {
        $procedure = Procedure::updateOrCreate(
            ['slug' => Str::slug('Electrocautery / Radiofrequency Devices')],
            [
                'title' => 'Electrocautery / Radiofrequency Devices',
                'slug' => Str::slug('Electrocautery / Radiofrequency Devices'),
                'introduction' => 'Electrocautery and radiofrequency devices are specialized dermatologic surgical instruments used to cut, coagulate, destroy, or remove abnormal skin tissue using controlled electrical or radiofrequency energy. These devices are commonly used in dermatology procedures for treating benign lesions, controlling bleeding, removing warts, and performing minor skin surgeries.',
                'what_is' => 'Electrocautery devices use heat generated by electrical current to destroy targeted tissue or stop bleeding during procedures. Radiofrequency devices use high-frequency energy to precisely treat skin lesions with minimal damage to surrounding tissue. These technologies are commonly used for removal of skin tags, warts, cysts, benign growths, vascular lesions, and certain cosmetic dermatology procedures. Treatments are generally performed in outpatient settings under local anesthesia.',
                'symptoms' => [
            ['value' => 'Benign skin growths or skin tags'],
            ['value' => 'Warts or raised skin lesions'],
            ['value' => 'Persistent bleeding from minor skin procedures'],
            ['value' => 'Cosmetic skin concerns requiring lesion removal'],
            ['value' => 'Small cysts or abnormal superficial skin growths'],
        ],
                'causes' => [
            ['value' => 'Viral skin infections such as warts'],
            ['value' => 'Benign overgrowth of skin tissue'],
            ['value' => 'Chronic skin irritation or friction-related lesions'],
            ['value' => 'Cosmetic or age-related skin changes'],
            ['value' => 'Abnormal skin cell growth requiring removal'],
        ],
                'condition_risks' => [
            ['value' => 'Mild pain, redness, or swelling after treatment'],
            ['value' => 'Temporary scabbing or crust formation'],
            ['value' => 'Pigmentation changes or mild scarring'],
            ['value' => 'Infection at the treatment site in rare cases'],
            ['value' => 'Recurrence of lesions requiring repeat procedures'],
            ['value' => 'Treatment Options'],
            ['value' => 'Electrocautery and radiofrequency devices are used in various dermatologic and cosmetic procedures for precise tissue removal and lesion management. Treatment selection depends on the type, size, and location of the lesion being treated. These procedures may be combined with biopsy, cryotherapy, laser therapy, or topical medications to optimize treatment outcomes and improve cosmetic results.'],
        ],
                'preventions' => [],
                'diagnosis_tests' => [],
                'treatment_overview' => '',
                'surgery_types' => [],
                'recovery_timeline' => [],
                'post_op_care' => [
            ['value' => 'Keeping the treated area clean and dry'],
            ['value' => 'Avoiding scratching or trauma to healing skin'],
            ['value' => 'Applying prescribed creams or dressings if advised'],
            ['value' => 'Monitoring for signs of infection or delayed healing'],
            ['value' => 'Follow-up dermatologic evaluation if required'],
        ],
                'surgery_risks' => [
            ['value' => 'Mild pain, redness, or swelling after treatment'],
            ['value' => 'Temporary scabbing or crust formation'],
            ['value' => 'Pigmentation changes or mild scarring'],
            ['value' => 'Infection at the treatment site in rare cases'],
            ['value' => 'Recurrence of lesions requiring repeat procedures'],
            ['value' => 'Treatment Options'],
            ['value' => 'Electrocautery and radiofrequency devices are used in various dermatologic and cosmetic procedures for precise tissue removal and lesion management. Treatment selection depends on the type, size, and location of the lesion being treated. These procedures may be combined with biopsy, cryotherapy, laser therapy, or topical medications to optimize treatment outcomes and improve cosmetic results.'],
        ],
                'long_term_outlook' => 'The long-term outlook after electrocautery or radiofrequency procedures is generally very positive. These treatments are effective for removing many benign skin lesions with minimal downtime and good cosmetic outcomes. Proper wound care, sun protection, and regular dermatologic follow-up help maintain healthy skin and reduce recurrence risk.',
                'conclusion' => '',
                'seo_title' => 'Electrocautery / Radiofrequency Devices',
                'seo_description' => 'Electrocautery and radiofrequency devices are specialized dermatologic surgical instruments used to cut, coagulate, destroy, or remove abnormal skin tissue using controlled electrical or radiofrequency energy. These devices are commonly used in dermatology procedures for treating benign lesions, controlling bleeding, removing warts, and performing minor skin surgeries.',
                'seo_keywords' => '',
                'is_active' => true,
            ]
        );
    }
}
