<?php

namespace Database\Seeders;

use App\Models\Condition;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MetastaticAdvancedStageCancersConditionSeeder extends Seeder
{
    public function run(): void
    {
        Condition::updateOrCreate(
            ['slug' => Str::slug('Metastatic / Advanced Stage Cancers')],
            [
                'name' => 'Metastatic / Advanced Stage Cancers',
                'slug' => Str::slug('Metastatic / Advanced Stage Cancers'),
                'h1' => 'Metastatic / Advanced Stage Cancers',
                'icon' => null,
                'cta_text' => null,
                'cta_link' => null,
                'about' => 'Metastatic or advanced stage cancers are cancers that have spread from their original site to other parts of the body such as the lungs, liver, bones, brain, or lymph nodes. Advanced cancers may affect multiple organs and often require comprehensive, multidisciplinary cancer care focused on controlling disease progression, relieving symptoms, and improving quality of life.',
                'about_more' => 'Adrenal cancer is a rare type of cancer that develops in the adrenal glands, which are small hormone-producing glands located above each kidney. These glands produce hormones that regulate blood pressure, metabolism, stress response, and other important body functions. Adrenal tumors may be benign or cancerous, and some tumors can produce excessive hormones leading to significant health complications. Neuroendocrine tumors (NETs) are a group of rare tumors that develop from neuroendocrine cells, which have features of both nerve cells and hormone-producing endocrine cells. These tumors can occur in various parts of the body, most commonly in the lungs, pancreas, digestive tract, and other hormone-producing organs. Some NETs grow slowly, while others can be more aggressive and spread to nearby organs or distant body parts. Cancer-related complications are serious health problems that develop as a result of advanced cancer or its treatment. Conditions such as malignant effusions, chronic cancer pain, and cancer cachexia can significantly affect organ function, nutrition, mobility, and overall quality of life. Early recognition and supportive cancer care are essential for symptom control and improving patient comfort. Pre-cancerous conditions are abnormal cellular or tissue changes that may increase the risk of developing cancer over time if left untreated. Conditions such as cervical dysplasia, certain polyps, and Barrett’s esophagus are considered precancerous because they can gradually progress into cancerous growths. Early diagnosis, monitoring, and timely treatment are important for preventing cancer development and maintaining long-term health. Multiple primary malignancies refer to the occurrence of two or more separate and distinct cancers in the same individual. These cancers may develop at the same time (synchronous) or at different times (metachronous) and are not caused by the spread of one cancer to another site. Management of multiple primary malignancies requires comprehensive evaluation, multidisciplinary cancer care, and individualized treatment planning. Treatment-related complications are medical conditions that may occur as side effects of cancer therapies such as chemotherapy, radiation therapy, surgery, immunotherapy, or targeted treatments. Complications such as neutropenia, mucositis, and lymphedema can affect immunity, nutrition, mobility, and overall quality of life. Early recognition and supportive care are important for reducing complications and improving recovery outcomes.',
                'overview' => 'Metastatic or advanced stage cancers are cancers that have spread from their original site to other parts of the body such as the lungs, liver, bones, brain, or lymph nodes. Advanced cancers may affect multiple organs and often require comprehensive, multidisciplinary cancer care focused on controlling disease progression, relieving symptoms, and improving quality of life. Adrenal cancer is a rare type of cancer that develops in the adrenal glands, which are small hormone-producing glands located above each kidney. These glands produce hormones that regulate blood pressure, metabolism, stress response, and other important body functions. Adrenal tumors may be benign or cancerous, and some tumors can produce excessive hormones leading to significant health complications. Neuroendocrine tumors (NETs) are a group of rare tumors that develop from neuroendocrine cells, which have features of both nerve cells and hormone-producing endocrine cells. These tumors can occur in various parts of the body, most commonly in the lungs, pancreas, digestive tract, and other hormone-producing organs. Some NETs grow slowly, while others can be more aggressive and spread to nearby organs or distant body parts. Cancer-related complications are serious health problems that develop as a result of advanced cancer or its treatment. Conditions such as malignant effusions, chronic cancer pain, and cancer cachexia can significantly affect organ function, nutrition, mobility, and overall quality of life. Early recognition and supportive cancer care are essential for symptom control and improving patient comfort. Pre-cancerous conditions are abnormal cellular or tissue changes that may increase the risk of developing cancer over time if left untreated. Conditions such as cervical dysplasia, certain polyps, and Barrett’s esophagus are considered precancerous because they can gradually progress into cancerous growths. Early diagnosis, monitoring, and timely treatment are important for preventing cancer development and maintaining long-term health. Multiple primary malignancies refer to the occurrence of two or more separate and distinct cancers in the same individual. These cancers may develop at the same time (synchronous) or at different times (metachronous) and are not caused by the spread of one cancer to another site. Management of multiple primary malignancies requires comprehensive evaluation, multidisciplinary cancer care, and individualized treatment planning. Treatment-related complications are medical conditions that may occur as side effects of cancer therapies such as chemotherapy, radiation therapy, surgery, immunotherapy, or targeted treatments. Complications such as neutropenia, mucositis, and lymphedema can affect immunity, nutrition, mobility, and overall quality of life. Early recognition and supportive care are important for reducing complications and improving recovery outcomes.',
                'symptoms' => [
            ['value' => 'Persistent fatigue and weakness'],
            ['value' => 'Unexplained weight loss and reduced appetite'],
            ['value' => 'Chronic pain affecting bones or organs'],
            ['value' => 'Breathing difficulty, swelling, or neurological symptoms depending on the area affected'],
            ['value' => 'Persistent fever, nausea, or worsening general health'],
            ['value' => 'Unexplained weight gain or weight loss'],
            ['value' => 'High blood pressure or persistent headaches'],
            ['value' => 'Muscle weakness and fatigue'],
            ['value' => 'Abdominal pain or swelling'],
            ['value' => 'Hormonal changes such as excessive hair growth, abnormal menstrual cycles, or elevated blood sugar levels'],
            ['value' => 'Persistent cough, sometimes with blood'],
            ['value' => 'Abdominal or stomach pain'],
            ['value' => 'A growing lump or swelling under the skin'],
            ['value' => 'Unexplained weight loss'],
            ['value' => 'Shortness of breath or wheezing'],
            ['value' => 'Persistent or severe pain'],
            ['value' => 'Shortness of breath due to fluid accumulation around the lungs or heart'],
            ['value' => 'Extreme weight loss and muscle wasting'],
            ['value' => 'Fatigue, weakness, and reduced physical activity'],
            ['value' => 'Loss of appetite and nutritional deficiency'],
            ['value' => 'Abnormal bleeding or discharge'],
            ['value' => 'Persistent acid reflux or heartburn'],
            ['value' => 'Difficulty swallowing or throat discomfort'],
            ['value' => 'Changes in bowel habits or rectal bleeding related to polyps'],
            ['value' => 'Many pre-cancerous conditions may not cause noticeable symptoms initially'],
            ['value' => 'Persistent fatigue and unexplained weight loss'],
            ['value' => 'Symptoms related to different affected organs or body systems'],
            ['value' => 'Chronic pain or discomfort'],
            ['value' => 'Swelling, lumps, or abnormal bleeding'],
            ['value' => 'Reduced physical stamina and overall weakness'],
            ['value' => 'Fever or frequent infections due to low immunity'],
            ['value' => 'Painful mouth sores or difficulty eating and swallowing'],
            ['value' => 'Swelling of the arms, legs, or affected body areas'],
            ['value' => 'Fatigue, weakness, or reduced physical function'],
            ['value' => 'Skin irritation, discomfort, or delayed healing after treatment'],
        ],
                'causes' => [
            ['value' => 'Delayed diagnosis or progression of untreated cancer'],
            ['value' => 'Aggressive cancer cell growth and spread'],
            ['value' => 'Genetic and molecular abnormalities in cancer cells'],
            ['value' => 'Resistance to previous cancer treatments'],
            ['value' => 'Spread of cancer through blood vessels or lymphatic system'],
            ['value' => 'Genetic and inherited syndromes'],
            ['value' => 'Hormonal and endocrine abnormalities'],
            ['value' => 'Family history of adrenal tumors or endocrine cancers'],
            ['value' => 'Abnormal cell growth within the adrenal glands'],
            ['value' => 'Most cases occur without a clearly identifiable cause'],
            ['value' => 'Genetic and inherited syndromes'],
            ['value' => 'Abnormal growth of hormone-producing cells'],
            ['value' => 'Family history of endocrine tumors'],
            ['value' => 'Hormonal and cellular mutations affecting neuroendocrine tissue'],
            ['value' => 'Most cases occur without a clearly identifiable cause'],
            ['value' => 'Advanced or metastatic cancer'],
            ['value' => 'Spread of cancer to organs, lymph nodes, or body cavities'],
            ['value' => 'Chronic inflammation and metabolic changes caused by cancer'],
            ['value' => 'Side effects of chemotherapy, radiation, or other cancer treatments'],
            ['value' => 'Reduced nutritional intake and cancer-related organ dysfunction'],
            ['value' => 'Human papillomavirus (HPV) infection'],
            ['value' => 'Chronic inflammation or long-term irritation of tissues'],
            ['value' => 'Gastroesophageal reflux disease (GERD) and acid reflux'],
            ['value' => 'Smoking, alcohol use, and unhealthy lifestyle habits'],
            ['value' => 'Family history and genetic predisposition'],
            ['value' => 'Genetic and inherited cancer syndromes'],
            ['value' => 'Previous exposure to chemotherapy or radiation therapy'],
            ['value' => 'Smoking, alcohol use, and unhealthy lifestyle habits'],
            ['value' => 'Long-term environmental or occupational carcinogen exposure'],
            ['value' => 'Increasing age and weakened immune function'],
            ['value' => 'Chemotherapy affecting healthy blood cells and tissues'],
            ['value' => 'Radiation therapy causing tissue inflammation or damage'],
            ['value' => 'Surgical removal of lymph nodes or cancer-related procedures'],
            ['value' => 'Immunotherapy or targeted therapy side effects'],
            ['value' => 'Reduced immune function and treatment-related tissue injury'],
        ],
                'risks' => [
            ['value' => 'Multi-organ involvement and organ dysfunction'],
            ['value' => 'Severe pain and reduced physical functioning'],
            ['value' => 'Nutritional deficiency and extreme weight loss'],
            ['value' => 'Increased risk of infections and treatment complications'],
            ['value' => 'Emotional distress and reduced quality of life'],
            ['value' => 'Spread of cancer to nearby organs or distant body parts'],
            ['value' => 'Severe hormonal imbalance affecting metabolism and blood pressure'],
            ['value' => 'Cardiovascular complications due to excess hormone production'],
            ['value' => 'Kidney and metabolic complications'],
            ['value' => 'Treatment-related side effects affecting hormonal function'],
            ['value' => 'Multiple endocrine neoplasia (MEN) syndromes'],
            ['value' => 'Von Hippel-Lindau syndrome'],
            ['value' => 'Neurofibromatosis type 1'],
            ['value' => 'Tuberous sclerosis complex'],
            ['value' => 'Cowden syndrome and other inherited genetic disorders'],
            ['value' => 'Respiratory distress from malignant pleural or pericardial effusions'],
            ['value' => 'Severe malnutrition and cachexia-related weakness'],
            ['value' => 'Reduced mobility and physical function'],
            ['value' => 'Emotional distress, anxiety, and poor quality of life'],
            ['value' => 'Increased hospitalization and advanced organ dysfunction'],
            ['value' => 'Progression to invasive cancer if untreated'],
            ['value' => 'Chronic tissue damage and inflammation'],
            ['value' => 'Increased need for repeated medical procedures or monitoring'],
            ['value' => 'Nutritional or digestive complications in gastrointestinal conditions'],
            ['value' => 'Emotional stress and anxiety related to cancer risk'],
            ['value' => 'Spread or progression of multiple cancers'],
            ['value' => 'Increased treatment complexity and organ-related complications'],
            ['value' => 'Reduced immunity and higher infection risk'],
            ['value' => 'Nutritional deficiency and physical weakness'],
            ['value' => 'Emotional stress and reduced quality of life'],
            ['value' => 'Severe infections and sepsis due to neutropenia'],
            ['value' => 'Nutritional deficiency and dehydration from mucositis'],
            ['value' => 'Chronic swelling and reduced mobility from lymphedema'],
            ['value' => 'Delayed cancer treatment due to treatment-related complications'],
            ['value' => 'Reduced quality of life and prolonged recovery'],
        ],
                'diagnosis' => [],
                'treatment' => [
            ['value' => 'Chemotherapy, targeted therapy, or immunotherapy'],
            ['value' => 'Radiation therapy for symptom control and tumor reduction'],
            ['value' => 'Surgical intervention in selected cases'],
            ['value' => 'Pain management and palliative care support'],
            ['value' => 'Multidisciplinary oncology care and supportive rehabilitation'],
            ['value' => 'Surgical removal of the adrenal tumor or gland'],
            ['value' => 'Chemotherapy and targeted therapy'],
            ['value' => 'Radiation therapy in selected cases'],
            ['value' => 'Hormonal control medications and endocrine management'],
            ['value' => 'Long-term oncology and endocrinology follow-up care'],
            ['value' => 'Surgical removal of the tumor when possible'],
            ['value' => 'Chemotherapy and targeted therapy'],
            ['value' => 'Hormone therapy and symptom-control medications'],
            ['value' => 'Radiation therapy or peptide receptor radionuclide therapy (PRRT)'],
            ['value' => 'Long-term oncology and endocrinology follow-up care'],
            ['value' => 'Drainage procedures for malignant effusions'],
            ['value' => 'Pain management and palliative care support'],
            ['value' => 'Nutritional therapy and cachexia management'],
            ['value' => 'Chemotherapy, radiation therapy, or targeted cancer treatment'],
            ['value' => 'Multidisciplinary supportive oncology care and symptom management'],
            ['value' => 'Regular screening and surveillance procedures'],
            ['value' => 'Surgical or endoscopic removal of abnormal tissue or polyps'],
            ['value' => 'Medications to control inflammation or acid reflux'],
            ['value' => 'Lifestyle modifications including smoking cessation and healthy diet'],
            ['value' => 'Long-term specialist follow-up and preventive care'],
            ['value' => 'Multidisciplinary oncology evaluation and treatment planning'],
            ['value' => 'Surgery, chemotherapy, or radiation therapy based on cancer type'],
            ['value' => 'Targeted therapy or immunotherapy when indicated'],
            ['value' => 'Supportive care, nutritional therapy, and symptom management'],
            ['value' => 'Long-term surveillance and genetic counseling when appropriate'],
            ['value' => 'Infection prevention and immune-supportive therapy'],
            ['value' => 'Pain management and oral care for mucositis'],
            ['value' => 'Compression therapy and rehabilitation for lymphedema'],
            ['value' => 'Nutritional support and hydration management'],
            ['value' => 'Multidisciplinary supportive oncology care and monitoring'],
        ],
                'recovery' => 'The long-term outlook for metastatic and advanced stage cancers depends on the type of cancer, extent of spread, response to treatment, and overall health condition. While advanced cancers may not always be curable, modern cancer therapies and supportive care can help control disease progression, reduce symptoms, improve comfort, and enhance quality of life. Continuous oncology follow-up and compassionate supportive care remain essential throughout treatment and recovery. Adrenal Cancer / Adrenal Tumors The long-term outlook for adrenal cancer depends on the type of tumor, stage of disease, hormone involvement, and response to treatment. Early diagnosis and specialized multidisciplinary care can improve treatment outcomes and quality of life. Continuous hormonal monitoring, imaging studies, supportive care, and regular follow-up are important for long-term recovery and prevention of recurrence. Neuroendocrine Tumors (NETs) The long-term outlook for neuroendocrine tumors depends on the type of tumor, stage of disease, hormone activity, and response to treatment. Many NETs can be managed successfully with early diagnosis and specialized multidisciplinary care. Continuous monitoring, hormonal evaluation, imaging studies, and supportive care are important for controlling symptoms, preventing complications, and improving long-term quality of life. Cancer-Related Complications (Malignant Effusions, Pain & Cachexia) The long-term outlook for cancer-related complications depends on the type and stage of cancer, overall health condition, and response to supportive treatment. Comprehensive symptom management, nutritional support, pain control, and palliative care can significantly improve comfort, quality of life, and functional well-being. Continuous oncology follow-up and individualized supportive care remain essential in advanced cancer management Pre-Cancerous Conditions (Cervical Dysplasia, Polyps & Barrett’s Esophagus) The long-term outlook for pre-cancerous conditions is generally very positive when abnormalities are detected early and treated appropriately. Routine screening, preventive healthcare, healthy lifestyle practices, and continuous medical follow-up play a vital role in reducing cancer risk and maintaining long-term health and well-being. Multiple Primary Malignancies The long-term outlook for multiple primary malignancies depends on the types of cancers involved, stage of disease, overall health condition, and response to treatment. Early detection and coordinated multidisciplinary cancer care can improve treatment outcomes and quality of life. Continuous monitoring, preventive healthcare, rehabilitation, and supportive care are important for long-term recovery and management. Treatment-Related Complications (Neutropenia, Mucositis & Lymphedema) The long-term outlook for treatment-related complications depends on the severity of symptoms, type of cancer therapy, and response to supportive care. Early management and continuous monitoring can significantly reduce complications, improve comfort, and support recovery during cancer treatment. Ongoing rehabilitation, preventive care, and specialist follow-up are important for maintaining long-term health and quality of life.',
                'sort_order' => 20,
                'is_active' => true,
                'meta_title' => 'Metastatic / Advanced Stage Cancers',
                'meta_description' => 'Metastatic or advanced stage cancers are cancers that have spread from their original site to other parts of the body such as the lungs, liver, bones, brain, or',
                'meta_keywords' => '',
            ]
        );
    }
}
