<?php

namespace Database\Seeders;

use App\Models\Procedure;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class NutritionalSupportinICUEnteralParenteralNutritionalSupportinICUEnteralParenteralSeeder extends Seeder
{
    public function run(): void
    {
        $procedure = Procedure::updateOrCreate(
            ['slug' => Str::slug('Nutritional Support in ICU (Enteral / Parenteral)  Nutritional Support in ICU (Enteral / Parenteral)')],
            [
                'title' => 'Nutritional Support in ICU (Enteral / Parenteral)  Nutritional Support in ICU (Enteral / Parenteral)',
                'slug' => Str::slug('Nutritional Support in ICU (Enteral / Parenteral)  Nutritional Support in ICU (Enteral / Parenteral)'),
                'introduction' => 'Nutritional support in the Intensive Care Unit (ICU) is a specialized critical care procedure used to provide essential nutrients, energy, proteins, vitamins, and fluids to critically ill patients who are unable to maintain adequate nutrition through normal oral intake. Enteral and parenteral nutrition support helps preserve organ function, improve healing, strengthen immunity, and support recovery during severe illness, trauma, surgery, or prolonged intensive care treatment. Extracorporeal Membrane Oxygenation (ECMO) is an advanced life-support procedure used in critically ill patients with severe heart or lung failure who do not respond adequately to conventional medical treatment. ECMO temporarily takes over the function of the heart and/or lungs by circulating blood through an external machine that removes carbon dioxide, adds oxygen, and returns oxygenated blood back to the body. This procedure is used as a bridge to recovery, surgery, transplantation, or advanced critical care management in selected high-risk cases. Bedside procedures such as chest tube insertion, paracentesis, and thoracentesis are minimally invasive medical interventions commonly performed in critically ill or hospitalized patients to remove abnormal fluid or air collections, relieve symptoms, improve organ function, and support diagnosis and treatment. These procedures are often carried out at the patient’s bedside under sterile conditions using imaging guidance when required. Critical care ultrasound and point-of-care imaging are advanced bedside diagnostic procedures used to rapidly evaluate organ function, fluid status, blood flow, cardiac activity, lung conditions, and emergency medical complications in critically ill patients. These imaging techniques provide real-time assessment and immediate clinical guidance, helping healthcare professionals make rapid decisions during emergency and intensive care management. Multidisciplinary ICU rounds and care protocols are coordinated critical care procedures involving collaborative evaluation, treatment planning, and continuous monitoring of critically ill patients by a team of healthcare specialists. These structured care approaches help improve patient safety, optimize treatment outcomes, enhance communication among healthcare providers, and ensure comprehensive management of complex medical conditions in the Intensive Care Unit (ICU).',
                'what_is' => 'Enteral nutrition involves delivering liquid nutritional formulas directly into the stomach or intestines through feeding tubes, while parenteral nutrition provides nutrients intravenously through central venous access when the digestive system cannot be used safely. These nutritional support procedures are commonly used in mechanically ventilated patients, severe trauma cases, sepsis, burns, gastrointestinal failure, neurological emergencies, and critically ill patients requiring prolonged ICU care. Nutritional therapy is carefully monitored and individualized based on metabolic requirements, organ function, fluid balance, and overall medical condition. ECMO is performed in intensive care units and specialized cardiac or critical care centers under continuous monitoring by multidisciplinary teams including intensivists, cardiothoracic surgeons, perfusionists, and critical care specialists. The procedure involves inserting large cannulas into major blood vessels to connect the patient to the ECMO circuit. There are two main types of ECMO: veno-venous (VV-ECMO) for severe respiratory failure and veno-arterial (VA-ECMO) for combined heart and lung support. ECMO is commonly used in conditions such as severe ARDS, cardiogenic shock, massive pulmonary embolism, severe myocarditis, or refractory cardiac arrest. Chest tube insertion involves placing a drainage tube into the pleural cavity to remove air, blood, pus, or fluid from around the lungs. Thoracentesis is a procedure used to remove excess fluid from the pleural space surrounding the lungs, while paracentesis involves draining fluid from the abdominal cavity. These procedures help relieve breathing difficulty, abdominal pressure, infection-related complications, and organ compression. Bedside procedures are commonly performed in intensive care units, emergency departments, medical wards, and critical care settings by trained physicians and critical care specialists. Point-of-care ultrasound (POCUS) involves the use of portable ultrasound devices at the patient’s bedside to assess the heart, lungs, abdomen, blood vessels, and other organs without transferring critically ill patients to imaging departments. Critical care ultrasound is commonly used for evaluating shock, respiratory failure, cardiac function, fluid accumulation, vascular access, trauma, and organ dysfunction. These procedures are widely performed in intensive care units, emergency departments, trauma centers, and operating rooms by intensivists, emergency physicians, anesthesiologists, and critical care specialists. Multidisciplinary ICU rounds involve daily bedside discussions and coordinated decision-making by intensivists, physicians, nurses, respiratory therapists, pharmacists, nutritionists, physiotherapists, infection control teams, and other specialists involved in patient care. ICU care protocols provide standardized clinical guidelines for managing ventilation, sedation, infection prevention, nutrition, fluid balance, hemodynamic support, organ dysfunction, rehabilitation, and emergency interventions. These procedures are designed to support evidence-based critical care management, improve recovery outcomes, and reduce ICU-related complications.',
                'symptoms' => [
            ['value' => 'Inability to eat or swallow safely'],
            ['value' => 'Severe weakness, malnutrition, or weight loss'],
            ['value' => 'Critical illness requiring prolonged intensive care support'],
            ['value' => 'Gastrointestinal dysfunction or impaired nutrient absorption'],
            ['value' => 'Increased nutritional demands during severe infection, trauma, or recovery'],
            ['value' => 'Severe respiratory failure unresponsive to ventilator support'],
            ['value' => 'Critical heart failure or cardiogenic shock'],
            ['value' => 'Severe low oxygen levels despite intensive respiratory treatment'],
            ['value' => 'Circulatory collapse or life-threatening cardiac instability'],
            ['value' => 'Multi-organ dysfunction due to severe cardiac or respiratory compromise'],
            ['value' => 'Shortness of breath or difficulty breathing'],
            ['value' => 'Chest pain or pressure due to fluid or air accumulation'],
            ['value' => 'Abdominal swelling, discomfort, or fluid buildup'],
            ['value' => 'Reduced oxygen levels or respiratory distress'],
            ['value' => 'Infection, trauma, or organ dysfunction requiring fluid drainage'],
            ['value' => 'Severe breathing difficulty or respiratory distress'],
            ['value' => 'Low blood pressure or circulatory instability'],
            ['value' => 'Chest pain, abdominal pain, or suspected internal bleeding'],
            ['value' => 'Shock, trauma, or altered organ function'],
            ['value' => 'Fluid overload, swelling, or signs of critical illness requiring urgent assessment'],
            ['value' => 'Severe critical illness requiring intensive monitoring and organ support'],
            ['value' => 'Respiratory failure, shock, or circulatory instability'],
            ['value' => 'Multi-organ dysfunction or complex medical conditions'],
            ['value' => 'Neurological deterioration or reduced consciousness'],
            ['value' => 'Severe infections, trauma, or postoperative complications requiring coordinated ICU care'],
        ],
                'causes' => [],
                'condition_risks' => [
            ['value' => 'Aspiration or respiratory complications during enteral feeding'],
            ['value' => 'Infection related to intravenous nutritional access'],
            ['value' => 'Electrolyte imbalance or metabolic complications'],
            ['value' => 'Liver dysfunction or blood sugar instability during prolonged nutritional therapy'],
            ['value' => 'Gastrointestinal intolerance, diarrhea, or feeding tube complications'],
            ['value' => 'Treatment Options'],
            ['value' => 'Nutritional support procedures in ICU focus on maintaining adequate calorie intake, preserving muscle mass, improving immune function, and supporting recovery from critical illness. Management may include enteral tube feeding, parenteral nutrition, fluid and electrolyte management, blood glucose monitoring, protein supplementation, vitamin and mineral replacement, gastrointestinal monitoring, and individualized dietary planning. Patients may also require multidisciplinary nutritional care involving intensivists, dietitians, gastroenterologists, nurses, and rehabilitation teams to optimize healing and reduce complications during critical care treatment.'],
            ['value' => 'Bleeding complications related to anticoagulation therapy'],
            ['value' => 'Blood clot formation within the ECMO circuit'],
            ['value' => 'Infection or bloodstream-related complications'],
            ['value' => 'Stroke, neurological injury, or organ dysfunction'],
            ['value' => 'Mechanical complications involving the ECMO equipment or vascular access'],
            ['value' => 'Treatment Options'],
            ['value' => 'ECMO procedures focus on temporarily supporting heart and lung function while the underlying condition is treated and organ recovery occurs. Management may include oxygenation support, mechanical ventilation adjustment, anticoagulation therapy, hemodynamic monitoring, infection control, fluid management, dialysis support, nutritional therapy, and intensive care monitoring. Patients may also require treatment for underlying conditions such as severe pneumonia, ARDS, myocarditis, cardiac failure, pulmonary embolism, trauma, or sepsis. Multidisciplinary critical care and rehabilitation support are essential to optimize survival and long-term recovery outcomes.'],
            ['value' => 'Bleeding or injury to surrounding organs and tissues'],
            ['value' => 'Infection at the procedure site'],
            ['value' => 'Lung collapse or air leakage during thoracic procedures'],
            ['value' => 'Fluid leakage or recurrence of fluid accumulation'],
            ['value' => 'Pain, discomfort, or temporary breathing difficulty after the procedure'],
            ['value' => 'Treatment Options'],
            ['value' => 'Bedside procedures focus on relieving pressure, improving breathing and circulation, removing abnormal fluid collections, and supporting recovery from underlying medical conditions. Management may include chest tube drainage systems, pleural or abdominal fluid removal, infection control, oxygen therapy, imaging guidance, laboratory analysis of drained fluid, pain management, and continuous monitoring. Patients may also require treatment for underlying conditions such as pleural effusion, pneumothorax, liver disease, trauma, infections, heart failure, or malignancy. Multidisciplinary care involving pulmonologists, intensivists, surgeons, radiologists, and rehabilitation teams is often essential for comprehensive treatment and recovery.'],
            ['value' => 'Limited diagnostic detail compared to advanced radiological imaging in certain cases'],
            ['value' => 'Operator-dependent interpretation variability'],
            ['value' => 'Difficulty obtaining clear images in some critically ill patients'],
            ['value' => 'Delayed diagnosis if findings are inconclusive'],
            ['value' => 'Need for additional imaging or specialist evaluation when required'],
            ['value' => 'Treatment Options'],
            ['value' => 'Critical care ultrasound and point-of-care imaging procedures focus on rapid bedside diagnosis, monitoring organ function, guiding emergency procedures, and supporting critical care decision-making. These procedures may assist in fluid resuscitation assessment, cardiac function evaluation, detection of pleural or abdominal fluid, vascular access guidance, trauma assessment, and respiratory monitoring. Point-of-care imaging also supports procedures such as central line insertion, thoracentesis, paracentesis, pericardiocentesis, and airway management. Patients may additionally receive intensive monitoring, respiratory support, hemodynamic stabilization, and multidisciplinary critical care management based on imaging findings.'],
            ['value' => 'Multi-organ failure or worsening critical illness'],
            ['value' => 'Ventilator-associated infections or ICU-related complications'],
            ['value' => 'Medication-related adverse effects or treatment delays'],
            ['value' => 'Prolonged ICU stay and reduced physical function'],
            ['value' => 'Increased risk of mortality in severe critical care conditions'],
            ['value' => 'Treatment Options'],
            ['value' => 'Multidisciplinary ICU rounds and care protocols focus on comprehensive patient assessment, coordinated treatment planning, prevention of complications, and optimization of critical care outcomes. Management may include respiratory support, hemodynamic stabilization, medication management, nutritional therapy, infection control measures, ventilator management, renal replacement therapy, rehabilitation services, and psychological support. Patients may also receive individualized care plans involving physiotherapy, occupational therapy, wound care, neurological monitoring, and long-term recovery planning. Continuous communication among multidisciplinary teams ensures safe, efficient, and evidence-based critical care delivery.'],
        ],
                'preventions' => [],
                'diagnosis_tests' => [],
                'treatment_overview' => '',
                'surgery_types' => [],
                'recovery_timeline' => [],
                'post_op_care' => [
            ['value' => 'Continuous monitoring of nutritional status and metabolic balance'],
            ['value' => 'Regular assessment of feeding tolerance and gastrointestinal function'],
            ['value' => 'Monitoring blood sugar, electrolytes, and organ function'],
            ['value' => 'Prevention of feeding-related infections or complications'],
            ['value' => 'Gradual transition to oral nutrition when clinically stable'],
            ['value' => 'Continuous cardiac, respiratory, and neurological monitoring'],
            ['value' => 'Monitoring for bleeding, clotting, or infection-related complications'],
            ['value' => 'Gradual weaning from ECMO support when organ function improves'],
            ['value' => 'Respiratory rehabilitation, physiotherapy, and nutritional support'],
            ['value' => 'Long-term critical care follow-up and recovery planning when required'],
            ['value' => 'Monitoring vital signs and respiratory status after the procedure'],
            ['value' => 'Regular assessment of drainage output and insertion sites'],
            ['value' => 'Pain management and infection prevention measures'],
            ['value' => 'Follow-up imaging or laboratory evaluation when required'],
            ['value' => 'Continued treatment and monitoring of the underlying medical condition'],
            ['value' => 'Continuous monitoring of clinical status and organ function'],
            ['value' => 'Follow-up imaging or diagnostic evaluation when required'],
            ['value' => 'Monitoring response to treatment and bedside interventions'],
            ['value' => 'Adjustment of critical care management based on imaging findings'],
            ['value' => 'Ongoing multidisciplinary critical care support and follow-up'],
            ['value' => 'Continuous monitoring of vital signs, organ function, and treatment response'],
            ['value' => 'Regular multidisciplinary review and adjustment of care plans'],
            ['value' => 'Prevention and monitoring of ICU-related complications'],
            ['value' => 'Rehabilitation support, nutritional management, and physiotherapy'],
            ['value' => 'Long-term follow-up and recovery planning after ICU discharge'],
        ],
                'surgery_risks' => [
            ['value' => 'Aspiration or respiratory complications during enteral feeding'],
            ['value' => 'Infection related to intravenous nutritional access'],
            ['value' => 'Electrolyte imbalance or metabolic complications'],
            ['value' => 'Liver dysfunction or blood sugar instability during prolonged nutritional therapy'],
            ['value' => 'Gastrointestinal intolerance, diarrhea, or feeding tube complications'],
            ['value' => 'Treatment Options'],
            ['value' => 'Nutritional support procedures in ICU focus on maintaining adequate calorie intake, preserving muscle mass, improving immune function, and supporting recovery from critical illness. Management may include enteral tube feeding, parenteral nutrition, fluid and electrolyte management, blood glucose monitoring, protein supplementation, vitamin and mineral replacement, gastrointestinal monitoring, and individualized dietary planning. Patients may also require multidisciplinary nutritional care involving intensivists, dietitians, gastroenterologists, nurses, and rehabilitation teams to optimize healing and reduce complications during critical care treatment.'],
            ['value' => 'Bleeding complications related to anticoagulation therapy'],
            ['value' => 'Blood clot formation within the ECMO circuit'],
            ['value' => 'Infection or bloodstream-related complications'],
            ['value' => 'Stroke, neurological injury, or organ dysfunction'],
            ['value' => 'Mechanical complications involving the ECMO equipment or vascular access'],
            ['value' => 'Treatment Options'],
            ['value' => 'ECMO procedures focus on temporarily supporting heart and lung function while the underlying condition is treated and organ recovery occurs. Management may include oxygenation support, mechanical ventilation adjustment, anticoagulation therapy, hemodynamic monitoring, infection control, fluid management, dialysis support, nutritional therapy, and intensive care monitoring. Patients may also require treatment for underlying conditions such as severe pneumonia, ARDS, myocarditis, cardiac failure, pulmonary embolism, trauma, or sepsis. Multidisciplinary critical care and rehabilitation support are essential to optimize survival and long-term recovery outcomes.'],
            ['value' => 'Bleeding or injury to surrounding organs and tissues'],
            ['value' => 'Infection at the procedure site'],
            ['value' => 'Lung collapse or air leakage during thoracic procedures'],
            ['value' => 'Fluid leakage or recurrence of fluid accumulation'],
            ['value' => 'Pain, discomfort, or temporary breathing difficulty after the procedure'],
            ['value' => 'Treatment Options'],
            ['value' => 'Bedside procedures focus on relieving pressure, improving breathing and circulation, removing abnormal fluid collections, and supporting recovery from underlying medical conditions. Management may include chest tube drainage systems, pleural or abdominal fluid removal, infection control, oxygen therapy, imaging guidance, laboratory analysis of drained fluid, pain management, and continuous monitoring. Patients may also require treatment for underlying conditions such as pleural effusion, pneumothorax, liver disease, trauma, infections, heart failure, or malignancy. Multidisciplinary care involving pulmonologists, intensivists, surgeons, radiologists, and rehabilitation teams is often essential for comprehensive treatment and recovery.'],
            ['value' => 'Limited diagnostic detail compared to advanced radiological imaging in certain cases'],
            ['value' => 'Operator-dependent interpretation variability'],
            ['value' => 'Difficulty obtaining clear images in some critically ill patients'],
            ['value' => 'Delayed diagnosis if findings are inconclusive'],
            ['value' => 'Need for additional imaging or specialist evaluation when required'],
            ['value' => 'Treatment Options'],
            ['value' => 'Critical care ultrasound and point-of-care imaging procedures focus on rapid bedside diagnosis, monitoring organ function, guiding emergency procedures, and supporting critical care decision-making. These procedures may assist in fluid resuscitation assessment, cardiac function evaluation, detection of pleural or abdominal fluid, vascular access guidance, trauma assessment, and respiratory monitoring. Point-of-care imaging also supports procedures such as central line insertion, thoracentesis, paracentesis, pericardiocentesis, and airway management. Patients may additionally receive intensive monitoring, respiratory support, hemodynamic stabilization, and multidisciplinary critical care management based on imaging findings.'],
            ['value' => 'Multi-organ failure or worsening critical illness'],
            ['value' => 'Ventilator-associated infections or ICU-related complications'],
            ['value' => 'Medication-related adverse effects or treatment delays'],
            ['value' => 'Prolonged ICU stay and reduced physical function'],
            ['value' => 'Increased risk of mortality in severe critical care conditions'],
            ['value' => 'Treatment Options'],
            ['value' => 'Multidisciplinary ICU rounds and care protocols focus on comprehensive patient assessment, coordinated treatment planning, prevention of complications, and optimization of critical care outcomes. Management may include respiratory support, hemodynamic stabilization, medication management, nutritional therapy, infection control measures, ventilator management, renal replacement therapy, rehabilitation services, and psychological support. Patients may also receive individualized care plans involving physiotherapy, occupational therapy, wound care, neurological monitoring, and long-term recovery planning. Continuous communication among multidisciplinary teams ensures safe, efficient, and evidence-based critical care delivery.'],
        ],
                'long_term_outlook' => 'The long-term outlook following ICU nutritional support depends on the severity of the underlying illness, duration of critical care treatment, nutritional status, and overall patient recovery. Early nutritional intervention, careful metabolic monitoring, rehabilitation support, physiotherapy, and long-term dietary management significantly help improve healing, preserve muscle strength, reduce complications, support organ recovery, and enhance overall quality of life. __________________ 21. ECMO (Extracorporeal Membrane Oxygenation) in Selected Cases ECMO (Extracorporeal Membrane Oxygenation) in Selected Cases ECMO (Extracorporeal Membrane Oxygenation) in Selected Cases The long-term outlook following ECMO support depends on the underlying medical condition, duration of organ failure, response to treatment, and overall patient health. Early intervention, advanced critical care management, rehabilitation support, infection prevention, physiotherapy, and multidisciplinary follow-up significantly help improve survival, restore organ function, reduce complications, and enhance overall quality of life. __________________ 22. Bedside Procedures (Chest Tube, Paracentesis, Thoracentesis) Bedside Procedures (Chest Tube, Paracentesis, Thoracentesis) Bedside Procedures (Chest Tube, Paracentesis, Thoracentesis) The long-term outlook following bedside procedures depends on the underlying disease, severity of fluid or air accumulation, response to treatment, and overall patient health. Early intervention, proper drainage management, infection prevention, rehabilitation support, and regular medical follow-up significantly help improve symptom relief, restore organ function, reduce complications, and enhance overall quality of life. ____________ 23. Critical Care Ultrasound & Point-of-Care Imaging Critical Care Ultrasound & Point-of-Care Imaging Critical Care Ultrasound & Point-of-Care Imaging The long-term outlook following critical care ultrasound and point-of-care imaging depends on the underlying medical condition, speed of diagnosis, and effectiveness of treatment interventions. Early bedside assessment, rapid clinical decision-making, continuous monitoring, rehabilitation support, and multidisciplinary critical care management significantly help improve survival, reduce complications, optimize organ function, and enhance overall quality of life. ______________ 24. Multidisciplinary ICU Rounds & Care Protocols Multidisciplinary ICU Rounds & Care Protocols Multidisciplinary ICU Rounds & Care Protocols The long-term outlook following multidisciplinary ICU care depends on the severity of critical illness, speed of intervention, effectiveness of coordinated treatment, and overall patient health. Early critical care intervention, structured ICU protocols, rehabilitation support, nutritional care, psychological support, and regular multidisciplinary follow-up significantly help improve survival, reduce complications, restore organ function, and enhance overall quality of life. ______________________',
                'conclusion' => '',
                'seo_title' => 'Nutritional Support in ICU (Enteral / Parenteral)  Nutritional Support in ICU (Enteral / Parenteral)',
                'seo_description' => 'Nutritional support in the Intensive Care Unit (ICU) is a specialized critical care procedure used to provide essential nutrients, energy, proteins, vitamins, and fluids to critically ill patients who are unable to maintain adequate nutrition through normal oral intake. Enteral and parenteral nutrition support helps preserve organ function, improve healing, strengthen immunity, and support recovery during severe illness, trauma, surgery, or prolonged intensive care treatment. Extracorporeal Membrane Oxygenation (ECMO) is an advanced life-support procedure used in critically ill patients with severe heart or lung failure who do not respond adequately to conventional medical treatment. ECMO temporarily takes over the function of the heart and/or lungs by circulating blood through an external machine that removes carbon dioxide, adds oxygen, and returns oxygenated blood back to the body. This procedure is used as a bridge to recovery, surgery, transplantation, or advanced critical care management in selected high-risk cases. Bedside procedures such as chest tube insertion, paracentesis, and thoracentesis are minimally invasive medical interventions commonly performed in critically ill or hospitalized patients to remove abnormal fluid or air collections, relieve symptoms, improve organ function, and support diagnosis and treatment. These procedures are often carried out at the patient’s bedside under sterile conditions using imaging guidance when required. Critical care ultrasound and point-of-care imaging are advanced bedside diagnostic procedures used to rapidly evaluate organ function, fluid status, blood flow, cardiac activity, lung conditions, and emergency medical complications in critically ill patients. These imaging techniques provide real-time assessment and immediate clinical guidance, helping healthcare professionals make rapid decisions during emergency and intensive care management. Multidisciplinary ICU rounds and care protocols are coordinated critical care procedures involving collaborative evaluation, treatment planning, and continuous monitoring of critically ill patients by a team of healthcare specialists. These structured care approaches help improve patient safety, optimize treatment outcomes, enhance communication among healthcare providers, and ensure comprehensive management of complex medical conditions in the Intensive Care Unit (ICU).',
                'seo_keywords' => '',
                'is_active' => true,
            ]
        );
    }
}
