-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3307
-- Generation Time: May 29, 2026 at 07:24 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nanotestabc`
--

-- --------------------------------------------------------

--
-- Table structure for table `doctors`
--

CREATE TABLE `doctors` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `practitioner_id` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `qualification` varchar(255) DEFAULT NULL,
  `designation` varchar(255) DEFAULT NULL,
  `kmc_number` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `experience_years` int(10) UNSIGNED DEFAULT NULL,
  `about` longtext DEFAULT NULL,
  `speciality_id` bigint(20) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `doctors`
--

INSERT INTO `doctors` (`id`, `practitioner_id`, `name`, `slug`, `photo`, `qualification`, `designation`, `kmc_number`, `location`, `experience_years`, `about`, `speciality_id`, `created_at`, `updated_at`) VALUES
(1, '7e3092a1-fb2c-11ef-8c5a-1aa0d50120e4-67', 'Dr Mohan M R', 'dr-mohan-m-r', 'doctors/24c21fbc-5e72-46cd-872f-2813d366bc92.webp', 'MBBS, MS, DNB - Orthopaedics', 'Consultant Orthopaedics and Reconstructive Surgeon', '63479', 'Both', 25, 'Dr. Mohan M.R is a Orthopedic surgeon in Hulimavu, Bangalore and has an experience of 24 years in this field. Dr. Mohan M.R practices at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. He completed MBBS from Bangalore Medical College and Research Institute, Bangalore in 2002 and MS - Orthopaedics from Bangalore Medical College and Research Institute, Bangalore in 2006.', 1, '2026-01-28 12:11:50', '2026-05-29 10:39:46'),
(2, NULL, 'Dr Belehallli Pavan', 'dr-belehallli-pavan', 'doctors/92eef1b3-19f5-4686-91ab-5d147a19ec99.webp', 'MBBS, MS - Orthopaedics', 'Consultant orthopaedic and Diabetic foot care', '77282', 'Both', 10, 'Dr. Belehalli Pavan is a Consultant Orthopaedic Surgeon practicing at Nano Hospitals Uttarahalli in Uttarahalli and Nano Hospital Hulimavu in Hulimavu, Bangalore. He specializes in bone and joint care, including the treatment of joint dislocations, hip pain, pediatric orthopedic conditions, and general musculoskeletal disorders. He completed his MBBS from M.S. Ramaiah Hospital and pursued DNB in Orthopedics/Orthopedic Surgery from Hosmat Hospital, Bangalore.', 1, '2026-01-28 12:19:13', '2026-04-09 12:30:32'),
(3, NULL, 'Dr Keshava Murthy D', 'dr-keshava-murthy-d', 'doctors/02e0d387-95ad-4a80-bc45-ce803cf4be51.webp', 'MBBS, MS - Orthopaedics', 'Bone and Joint care- Consultant orthopaedic surgeon', '95216', 'Both', 10, 'Dr. Keshava Murthy is a Orthopedic surgeon in Uttarahalli, Bangalore and has an experience of 14 years in this field. Dr. Keshava Murthy practices at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore. He completed MBBS from Adichunchangiri Institute of Medical Sciences, Mandya in 2012,Diploma in Orthopaedics from Devaraj URS Medical College - Kolar in 2017 and DNB - Orthopedics/Orthopedic Surgery from National Board of Examination, India in 2019.', 1, '2026-01-29 11:30:04', '2026-05-07 10:04:39'),
(4, NULL, 'Dr Prashanth S Gorur', 'dr-prashanth-s-gorur', 'doctors/f8587c28-f08b-4d0f-beac-2617814b4e68.webp', 'MBBS, MS - Orthopaedics', 'Fellowship in Arthroscopy & Sport Injuries & Shoulder Surgery', '61480', 'Both', 16, 'Dr. Prashanth Gorur is an orthopaedic consultant specializing in arthroscopy and sports injuries. Having done his medical and post-graduate training at Bangalore medical college, he went on to pursue his passion by doing a prestigious fellowship in arthroscopy and sports medicine in Pune and shoulder surgery training in japan', 1, '2026-02-02 13:09:38', '2026-03-26 10:34:57'),
(5, NULL, 'Dr Suhas Raj S', 'dr-suhas-raj-s', 'doctors/8de7c71a-80e1-4c25-b3ea-e5f5c741f7bf.webp', 'MBBS, MD - General Medicine, DM - Cardiology', 'Consultant Cardiologist', '64485', 'Uttarahalli', 13, 'Confident and Disciplined Physician and Cardiologist who graduated undergraduation, postgraduation and Super speciality from prestigious Government colleges & hospitals. Ability to develop quick and Good rapport with patients and families with bedside clinical experience in ICU and ward settings and also good hands-on experience in Cath-Lab', 5, '2026-02-02 13:13:44', '2026-03-26 07:02:12'),
(6, NULL, 'Dr Manish Pai', 'dr-manish-pai', 'doctors/48189d40-d8a6-486f-a4e6-4dc5b7b8a04e.webp', 'MBBS, DM - Neurology', 'Neuro and Spine surgeon', '64472', 'Both', 25, 'Dr. Manish Ganesh Pai is a Neurosurgeon in Manipal Hospitals Hebbal, Bangalore and has an experience of 25 years in this field. Dr. Manish Ganesh Pai practices at Manipal Hospital in Hebbal, Bangalore. He completed MBBS from Rajiv Gandhi University of Health Sciences in 2001,MS - General Surgery from The Tamil Nadu Dr. M.G.R. Medical University (TNMGRMU) in 2008 and MCh - Neuro Surgery from Sree Chitra Tirunal Institute for Medical Sciences & Technology, Trivandrum in 2011.', 6, '2026-02-02 13:16:42', '2026-04-09 12:30:01'),
(7, NULL, 'Dr Muruli Krishna', 'dr-muruli-krishna', 'doctors/01KGW2939TZN8RCE6CQF4BCJCX.webp', 'MBBS, MS - Vascular Surgery', 'Consultant Vascular Surgeon', '62401', 'Both', 19, 'Dr. Muralikrishna is a renowned Vascular Surgeon and is an Associate Professor at the Jayadeva Institute of Cardiology, Bangalore. He has trained in India and abroad (Europe) and is passionate about dialysis vascular access which is the \"Achilles heel\" of dialysis. ', 12, '2026-02-02 13:18:49', '2026-03-26 07:05:53'),
(8, NULL, 'Dr Arun Kumar A', 'dr-arun-kumar-a', 'doctors/dc9ccbde-b68e-4a45-8eb8-da10e652be11.webp', 'MBBS, MS - Vascular Surgery', 'Consultant Vascular Surgeon', '107818', 'Hulimavu', 12, 'Dr. Arun Kumar A is a Vascular Surgeon in Bangalore with 12 years of experience in this field. He practices at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals in Hulimavu, Bangalore. He completed his MBBS from Devaraj URS Medical College, Kolar in 2014, MS in General Surgery from JSS University, Mysore in 2018, and MCh in Vascular Surgery from Sri Ramachandra University, Chennai in 2022.', 12, '2026-02-02 13:27:11', '2026-03-26 07:07:03'),
(9, NULL, 'Dr Sailendra', 'dr-sailendra', 'doctors/6ef4abcd-e058-4bf6-b3e9-80dc4d17510b.webp', 'MBBS, DNB - Radiology', 'Consultant Radiologist', '67846', 'Both', NULL, NULL, 24, '2026-02-02 13:28:43', '2026-02-10 05:31:43'),
(10, NULL, 'Dr Subhash', 'dr-subhash', 'doctors/78c6c287-e13f-48ba-9a9f-461b9bbd52e1.webp', 'MBBS, DNB - Radiology', 'Consultant Radiologist', 'TMN20080001331KTK', 'Hulimavu', NULL, NULL, 24, '2026-02-02 13:29:57', '2026-02-16 06:56:55'),
(11, NULL, 'Dr Sailaja V', 'dr-sailaja-v', 'doctors/33b8bab3-9691-455f-87d4-a3fb162e1a20.webp', 'M.B.B.S, D.C.H (Dnb)', 'Consultant Paediatrician And Neonatologist', '85385', 'Both', 20, 'Dr. Sailaja V is a Pediatrician in Bangalore with 20 years of experience in this field. She practices at Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore, Nano Hospitals in Hulimavu, Bangalore, and Nano Hospital in Uttarahalli, Bangalore. She completed her MBBS from Narayana Medical College, Nellore in 2006 and Diploma in Child Health (DCH) from Kurnool Medical College, Kurnool in 2009.', 2, '2026-02-02 13:32:27', '2026-04-09 12:25:54'),
(12, '5157f0c1-4a8c-11f0-b606-be4acd1da41e-20', 'Dr Kruthika Prasad', 'dr-kruthika-prasad', NULL, 'MBBS, MD - Pathology', 'Consultant Pathologist', '82886', 'Both', NULL, NULL, 16, '2026-02-02 13:36:17', '2026-05-29 11:35:03'),
(13, NULL, 'Dr Pratibha Setty', 'dr-pratibha-setty', 'doctors/2a8c4e1c-bbcc-4d41-8048-ed74aaf5b360.webp', 'MBBS, DNB, DM (Gastroenterology)', 'Consultant Gastroenterologist', '53359', 'Both', 22, 'Dr. Pratibha Setty is a Gastroenterologist and Internal Medicine specialist in Bangalore with 22 years of experience in these fields. She practices at Nano Hospitals in Hulimavu, Bangalore and Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore. She completed her MBBS from Devaraj URS Medical College, Kolar in 1999, DNB in General Medicine from the National Board of Examination in 2004, and DM in Gastroenterology from Gandhi Medical College, Hyderabad in 2015.', 9, '2026-02-02 13:38:36', '2026-03-26 07:10:33'),
(14, NULL, 'Dr Dhanalaxmi Aniyappanavar', 'dr-dhanalaxmi-aniyappanavar', NULL, 'MBBS, MD - Microbiology', 'Consultant Microbiologist', '71181', 'Both', 21, 'Dr. Dhanalaxmi Aniyappanavar is a medical doctor specializing in Clinical Microbiology, with eight years of experience in teaching medical students in addition to managing the Microbiology Department in a multispeciality hospital. She practices at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. Her areas of interest include laboratory medicine, medical writing, clinical research, antibiotic resistance, antibiotic policy development, hospital infection control, and medical education.', 25, '2026-02-02 13:40:52', '2026-03-26 07:11:18'),
(15, NULL, 'Dr Sarada Patil', 'dr-sarada-patil', NULL, 'MBBS, MD - Pathology', 'Consultant Pathologist', '66391', 'Both', NULL, NULL, 25, '2026-02-02 13:44:36', '2026-02-02 13:44:36'),
(16, NULL, 'Dr Shama Mohan', 'dr-shama-mohan', 'doctors/dba6ff8f-26d1-4a15-be93-7e52b9cd3c2c.webp', 'MBBS, MS - Plastic Surgery', 'Reconstructive Surgeon', '24578', 'Both', 12, 'Dr. Shama Mohan is an Oral and Maxillofacial Surgeon in Bangalore with 12 years of experience in this field. She practices at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. She completed her BDS from Rajiv Gandhi University of Health Sciences in 2014 and MDS in Oral & Maxillofacial Surgery from Rajiv Gandhi University of Health Sciences in 2019.', 19, '2026-02-02 13:46:16', '2026-04-10 11:06:10'),
(17, NULL, 'Dr Niti Raizada', 'dr-niti-raizada', 'doctors/ac546832-2090-4b21-bbd1-1737286329e2.webp', 'MBBS, MD - Oncology', 'Consultant Oncologist', '92267', 'Both', 29, 'Dr. Niti is a Senior Consultant Medical Oncologist and Hemato-Oncologist with over 16 years of experience in the field of oncology. She practices at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. She is a Gold Medalist and a President of India Awardee, and has served as a Principal Investigator in numerous multinational oncology clinical trials.\n\nHer areas of special interest include thoracic oncology, gastrointestinal oncology, breast oncology, gynaecological oncology, and bone marrow transplant. She has delivered several presentations at prestigious forums such as the American Society of Clinical Oncology (ASCO), UICC, and INCTR. In addition to her clinical and research work, she serves on the Editorial Board of the Journal of Medical Science and Research and regularly contributes articles on oncology to various newspapers, while actively participating in social and interdepartmental programs.', 11, '2026-02-02 13:47:34', '2026-03-26 07:12:39'),
(18, NULL, 'Dr K N Prajwal', 'dr-k-n-prajwal', 'doctors/3788ec10-6abb-47e1-ab2a-e69cdbf8b58a.webp', 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '107822', 'Both', 12, 'Dr. Prajwal K N is an Orthopedic Surgeon, Joint Replacement Surgeon, and Spine Surgeon with 12 years of overall experience, including 7 years as a specialist. He holds an MBBS and MS in Orthopaedics, and his medical registration is verified. He practices at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore.\n\nHe has worked in both government and private institutions for eight years and has received formal training in advanced joint replacement at a high-volume center. His areas of specialization include joint replacement surgery, management of complex and advanced fractures, sports injuries, and spine injuries.', 1, '2026-02-02 13:49:03', '2026-03-26 07:13:10'),
(19, NULL, 'Dr K S Manjunath', 'dr-k-s-manjunath', 'doctors/8058be16-2f50-4cff-8e2e-519c1d985fa6.webp', 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '18986', 'Uttarahalli', 24, 'Dr. K.S. Manjunath is a Professor and Head of the Department of Orthopaedics at Bangalore Medical College and Research Centre. He practices at Nano Hospital in Uttarahalli, Bangalore. He is an experienced Orthopaedic specialist with expertise in joint replacement, fracture management, and comprehensive orthopaedic care.', 1, '2026-02-02 13:50:57', '2026-03-26 07:15:02'),
(20, NULL, 'Dr Viresh Murgodi', 'dr-viresh-murgodi', 'doctors/fe17350c-fdc4-44f7-88f0-f1a97a9ea3ce.webp', 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '90066', 'Both', 10, 'Dr. Viresh Murgodi is a Consultant specializing in Arthroscopy, Sports Medicine, Joint Replacement, and Advanced Trauma care. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. His clinical expertise includes advanced arthroscopic procedures, management of sports-related injuries, primary and revision joint replacement surgeries, and treatment of complex trauma cases.', 1, '2026-02-02 13:52:01', '2026-02-16 12:59:56'),
(21, NULL, 'Dr Ajay N Naidu', 'dr-ajay-n-naidu', 'doctors/6b8d77c9-ddf2-485b-88c9-3703d69f1068.webp', 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '128998', 'Uttarahalli', 7, 'Dr. Ajay N (MBBS, MS, DNB) is an Orthopaedic and Joint Replacement Surgeon with advanced fellowship training in Robotic Joint Replacement from Mumbai and Revision Hip and Knee Arthroplasty with Infection Management from Hungary. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore.\n\nHe provides comprehensive orthopaedic care, including management of complex trauma and fractures, treatment of hip, knee, shoulder, and other joint pain, spine care for back and neck pain, arthritis and sports injuries, robotic and conventional joint replacement surgeries, as well as revision arthroplasty and infection management.', 1, '2026-02-02 13:53:03', '2026-02-16 13:02:54'),
(22, 'dcfe76a1-60b0-11f0-a8b1-f695b13dab7d-24', 'Dr A Ramalingaiah', 'dr-a-ramalingaiah', 'doctors/2d68fd2a-a09c-4be3-9f7f-7f3d48b5c176.webp', 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '22719', 'Uttarahalli', 33, 'Dr. Ramalingaiah A is one of the best Orthopedic Doctors in Banashankari, Bangalore. He has had many happy patients in his 33 years of journey as an Orthopedic Doctor. He is a qualified M.S (Ortho). He currently consults at Nano Hospital.', 1, '2026-02-02 13:54:01', '2026-05-29 11:47:01'),
(23, NULL, 'Dr Sushmitha K', 'dr-sushmitha-k', 'doctors/c4fcddbd-c70c-4613-8017-675ad9048c52.webp', 'MBBS, MD - Paediatrics', 'Consultant Paediatrician', '119988', 'Uttarahalli', NULL, NULL, 2, '2026-02-02 13:55:26', '2026-02-16 07:02:30'),
(24, NULL, 'Dr Naveen Kumar', 'dr-naveen-kumar', 'doctors/c949f064-96c9-4ad1-9ce6-64606e22f653.webp', 'MBBS, MD - Paediatrics', 'Consultant Paediatrician', '137522', 'Uttarahalli', 8, 'Dr. Naveen Kumar G is a Pediatrician in Uttarahalli, Bangalore, with 8 years of experience in this field. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore. He completed his MBBS from Rajiv Gandhi University of Health Sciences, Bangalore in 2018 and MD in Pediatrics from Rajiv Gandhi University of Health Sciences in 2022.', 2, '2026-02-02 13:56:51', '2026-02-16 13:07:25'),
(25, NULL, 'Dr Arjun S Kashyap', 'dr-arjun-s-kashyap', 'doctors/c891b0de-8358-4f41-9bc3-58c380188cd7.webp', 'MBBS, MD - Pulmonology', 'Consultant Pulmonologist', '89509', 'Uttarahalli', 16, 'Dr. Arjun S Kashyap is a Pulmonologist in Bangalore with 16 years of experience in this field. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals in Hulimavu, Bangalore. He completed his MBBS from Rajiv Gandhi University of Health Sciences, Bangalore, India in 2010 and DNB in Pulmonary Medicine from the National Board (DNB), New Delhi in 2015.', 7, '2026-02-02 13:58:49', '2026-02-16 13:09:45'),
(26, NULL, 'Dr Adarsh M S', 'dr-adarsh-m-s', 'doctors/81505349-1108-4594-9bd8-7c9f61303054.webp', 'MBBS, MS (Gen Surgery) DNB', 'Consultant Vascular & Endovascular Surgeon', '89509', 'Uttarahalli', 11, 'Dr. Adarsh M S is a Vascular Surgeon in Bangalore with 12 years of experience in this field. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore. He completed his MBBS from JSS Medical College in 2014, MS in General Surgery from Kempegowda Institute of Medical Sciences (KIMS), Bangalore in 2018, and DNB in Vascular Surgery from the National Board of Examination, India in 2022.', 12, '2026-02-02 14:01:29', '2026-05-18 11:56:34'),
(27, NULL, 'Dr Vivek K U', 'dr-vivek-k-u', NULL, 'MBBS, MD - Pulmonology', 'Consultant Pulmonologist', '2015', 'Uttarahalli', 12, 'Dr. Vivek K U is a Pulmonologist in Bangalore with 14 years of experience in this field. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore. He completed his MBBS from Rajiv Gandhi University of Health Sciences in 2011 and MD in Pulmonary Medicine from Punjab University, Chandigarh in 2015.', 7, '2026-02-02 14:02:37', '2026-02-16 13:20:22'),
(28, NULL, 'Dr Sanjana Kumar', 'dr-sanjana-kumar', 'doctors/ed4c7767-87e2-450f-b015-ad25f54b8a0b.webp', 'MBBS, MS - Gynaecology', 'Consultant Gynaecologist', '119400', 'Both', 9, 'Dr. Sanjana Kumar is a Gynecologist and Obstetrician in Bangalore with 9 years of experience in these fields. She is a Consultant at Nano Hospital in Uttarahalli, Bangalore. She completed her MBBS from Rajiv Gandhi University of Health Sciences, Bengaluru in 2017, MS in Obstetrics & Gynaecology from Rajiv Gandhi University of Health Sciences, Bengaluru in 2021, and DNB in Obstetrics & Gynecology from NBEMS, New Delhi in 2021.\n', 3, '2026-02-02 14:03:56', '2026-05-21 13:07:32'),
(29, NULL, 'Dr Swathi Iyenger', 'dr-swathi-iyenger', NULL, 'MBBS, MS - Gynaecology', 'Consultant Gynaecologist', '124040', 'Uttarahalli', 8, 'Dr. Swathi L Iyengar is a Gynecologist and Obstetrician in Bangalore with 8 years of experience in these fields. She is a Consultant at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore. She completed her MBBS from Rajiv Gandhi University of Health Sciences in 2018 and MS in Obstetrics & Gynaecology from RajaRajeswari Medical College in 2022.\n', 3, '2026-02-02 14:05:05', '2026-02-16 13:23:52'),
(30, NULL, 'Dr Greeshma G', 'dr-greeshma-g', NULL, 'MBBS, MS - Gynaecology', 'Consultant Gynaecologist', '123445', 'Both', 8, 'Dr. Greeshma G is an Obstetrician in Bangalore with 6 years of experience in this field. She is a Consultant at Nano Hospital in Uttarahalli, Bangalore. She completed her MBBS from Rajiv Gandhi University of Health Sciences, Bangalore in 2018 and MS in Obstetrics & Gynaecology from Dr. NTR University of Health Sciences, Andhra Pradesh in 2021.', 3, '2026-02-02 14:06:40', '2026-02-16 13:36:35'),
(31, '3dae1591-fd98-11ef-a182-9a1957157d81-82', 'Dr Harsha K J', 'dr-harsha-k-j', 'doctors/31e2c0cc-fce3-4f87-9f01-17e688f86e20.webp', 'MBBS, DM - Neurology', 'Consultant Neurologist', '71827', 'Uttarahalli', 14, 'Dr. Harsha K J is a Stroke Specialist in Bangalore with 17 years of experience in this field. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore, where he consults and provides specialized stroke care. He completed his MBBS from JJM Medical College in 2005, MD from MS University of Baroda in 2010, and DM from Sree Chitra Tirunal Institute for Medical Sciences & Technology, Trivandrum in 2012. He further completed a Stroke Fellowship from Canada in 2017.', 6, '2026-02-02 14:08:11', '2026-05-29 11:49:40'),
(32, NULL, 'Dr Harsha Kumar', 'dr-harsha-kumar', 'doctors/30c76ab5-b0c9-41be-963d-af25b707f5f9.webp', 'MBBS, MD (INTERNAL MEDICINE)(NEPHROLOGY PGI)', 'CONSULTANT NEPHROLOGIST AND TRANSPLANT PHYSICIAN', '76636', 'Hulimavu', 19, 'Dr. Harsha is a Consultant Nephrologist at Nano Hospitals in Hulimavu, Bangalore. An MBBS, MD, and DM, he is highly qualified and experienced in performing a wide range of nephrology procedures. His expertise includes insertion of temporary hemodialysis catheters (internal jugular and femoral), placement of tunneled cuffed catheters, kidney biopsies, and the use of ultrasound for nephrology interventions.\n\nHe manages conditions such as acute kidney injury, chronic kidney disease, general nephrology disorders, hemodialysis, peritoneal dialysis, and renal transplantation. Known for his compassionate approach, Dr. Harsha believes in delivering patient-centered care with clinical prudence. In addition to his clinical practice, he has several presentations and publications to his credit', 26, '2026-02-02 14:11:01', '2026-02-17 06:29:40'),
(34, NULL, 'Dr Vishwas H V', 'dr-vishwas-h-v', NULL, 'MBBS, DM - Neurology', 'Neuro and Spine surgeon', '76352', 'Uttarahalli', 17, 'Dr. Vishwas H V (DNB – Neurosurgery, FRCS, FMISS, FSFN) is a highly skilled Neuro and Spine Surgeon with extensive international training. He completed his neurosurgical training at NH, Bangalore, followed by a Fellowship in Minimally Invasive Spine Surgery in South Korea and the United Kingdom. He also completed the prestigious Royal College Fellowship in Functional Neurosurgery in the United Kingdom. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore.\n\nHis areas of expertise in neurosurgery include management of brain tumors, traumatic brain injuries, Parkinson’s disease and other movement disorders, epilepsy, and chronic pain. In spine surgery, he specializes in back pain management using non-invasive methods such as spinal injections and ablations, minimally invasive spine surgery, endoscopic spine surgery, treatment of spine injuries, and management of spinal tumors.', 6, '2026-02-02 14:13:23', '2026-04-09 12:34:01'),
(35, NULL, 'Dr Kalyani Dilip Karkare', 'dr-kalyani-dilip-karkare', 'doctors/5761535a-a59d-4a15-bed8-b5449d137c35.webp', 'MBBS, DM - Neurology', 'Consultant Neurologist and Epilepsy Specialist', 'MAH20040000584KTK', 'Both', NULL, 'She is a neurologist with a fellowship in electroencephalography and a special interest in epilepsy. Apart from general neurology, adult and pediatric epilepsies, she specialist in epilepsy surgery planning for both lesion and non-lesional epilepsies.', 6, '2026-02-02 14:14:39', '2026-02-17 06:47:41'),
(36, NULL, 'Dr Nayana R', 'dr-nayana-r', 'doctors/f274b907-884f-4017-b46b-007296745344.webp', 'MBBS, MD -  Internal Medicine', 'Consultant Physician', '114248', 'Uttarahalli', 10, 'Dr. Nayana R is a General Physician and Internal Medicine in Uttarahalli, Bangalore and has an experience of 10 years in these fields. Dr. Nayana R practices at Nano Hospital in Uttarahalli, Bangalore. She completed MBBS from V I M S Bellary in 2016 and MD - General Medicine from B L D E University in 2021.\n\nSome of the services provided by the doctor are: GENERAL MEDICINE and Viral Fever etc', 28, '2026-02-02 14:16:53', '2026-04-10 11:23:20'),
(37, NULL, 'Dr Siddharth Gosavi', 'dr-siddharth-gosavi', 'doctors/5fd3f00e-752e-4ed7-857b-581e10cdd48f.webp', 'MBBS, MD - Internal Medicine', 'Consultant in Internal Medicine', '114893', 'Uttarahalli', 10, 'Dr. Siddharth Gosavi is a Consultant in Internal Medicine in Bangalore with 10 years of experience in this field. He practices at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore. He completed his MBBS from Rajiv Gandhi University of Health Sciences in 2016, MD in General Medicine from Rajiv Gandhi University of Health Sciences in 2021, and DNB in General Medicine from the National Board of Examination in 2021.\n', 28, '2026-02-02 14:18:30', '2026-05-12 09:56:28'),
(38, NULL, 'Dr Anusha V G', 'dr-anusha-v-g', 'doctors/76de901e-1b85-498c-8abe-c65f6a485280.webp', 'MBBS, MD - Psychiatry', 'Consultant Psychiatrist', '115609', 'Uttarahalli', NULL, NULL, 16, '2026-02-02 14:21:04', '2026-05-12 10:16:11'),
(39, NULL, 'Dr Vibha B', 'dr-vibha-b', 'doctors/6828a470-b91c-4e3e-9598-fc8aff600134.webp', 'Consultant ENT Surgeon', 'MBBS, MS - ENT', '122344', 'Uttarahalli', 8, 'Dr. Vibha B is a ENT/ Otorhinolaryngologist in Uttarahalli, Bangalore and has an experience of 8 years in this field. Dr. Vibha B practices at Nano Hospital in Uttarahalli, Bangalore. She completed MBBS from Rajiv Gandhi University of Health Sciences in 2018 and MS - ENT from Rajiv Gandhi University of Health Sciences in 2022', 15, '2026-02-02 14:22:08', '2026-03-26 07:31:43'),
(40, NULL, 'Dr Ajitha Tavvala', 'dr-ajitha-tavvala', 'doctors/79208e69-c3e5-4925-a7fc-a9060b2fb234.webp', 'MBBS, MS - ENT', 'Consultant ENT Surgeon', '109989', 'Uttarahalli', 11, 'Dr. Ajitha Tavvala is a Consultant ENT and Otorhinolaryngologist in Bangalore with 11 years of experience in this field. She practices at Nano Hospital in Uttarahalli, Bangalore. She completed her MBBS from Rajiv Gandhi University of Health Sciences, Bangalore in 2015, MS in ENT from Adichunchanagiri Institute of Medical Sciences in 2022, and DNB in ENT from the National Board of Examination in 2022.\n', 15, '2026-02-02 14:23:27', '2026-02-17 07:00:56'),
(41, NULL, 'Dr Vani Yepuri', 'dr-vani-yepuri', 'doctors/20062698-2ef4-40e4-bd63-185a6b35c991.webp', 'MBBS, MD - Dermatology', 'Consultant Dermatologist', '93598', 'Uttarahalli', 17, 'Dr. Vani Yepuri is a Consultant Dermatologist with over three years of experience in clinical dermatology and aesthetic practice. She consults at Nano Hospital in Uttarahalli, Bangalore. She has a special interest in Aesthetic Dermatology and performs a wide range of procedures including laser treatments, Botox, fillers, chemical peels, and vitiligo surgeries.\n\nShe completed her MBBS from Rangaraya Medical College, Kakinada (2001–2007), followed by Postgraduate training in Dermatology, Venereology & Leprology (DDVL) from Rangaraya Medical College, Kakinada (2009–2011). She further pursued a Fellowship in Medical Cosmetology from Venkat Charmalaya Centre for Advanced Dermatology under Rajiv Gandhi University of Health Sciences, Bangalore (2012–2013).', 13, '2026-02-02 14:24:28', '2026-02-17 07:03:53'),
(42, NULL, 'Dr Sharath C T', 'dr-sharath-c-t', 'doctors/ed7c6460-2760-4e95-8924-f7d37a0c4ecd.webp', 'MBBS, MS - Urology', 'Consultant Urologist', '95039', 'Uttarahalli', 14, 'Dr. Sharath C T is a Urologist in Bangalore with 14 years of experience in this field. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore. He completed his MBBS from Hassan Institute of Medical Sciences in 2012, MS in General Surgery from Coimbatore Medical College in 2016, and DNB in Urology/Genito-Urinary Surgery from the National Board of Examination, India in 2020', 8, '2026-02-02 14:25:23', '2026-02-17 07:06:20'),
(43, NULL, 'Dr Sanjay R P', 'dr-sanjay-r-p', 'doctors/2d3c776e-83a1-4fde-a866-f0b099964eb0.webp', 'MBBS, MS - Urology', 'Consultant Urologist', '49790 ', 'Uttarahalli', 28, 'Dr. Sanjay R P is a Urologist and Andrologist in Bangalore with 28 years of experience in these fields. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore. He completed his MBBS from Mahadevappa Rampure Medical College, Gulbarga in 1998, MS in General Surgery from Bangalore Medical College and Research Institute, Bangalore in 2004, and MCh in Urology from the Institute of Nephro Urology in 2015.', 8, '2026-02-02 14:27:50', '2026-05-21 10:34:53'),
(47, NULL, 'Dr Kishan Rao K', 'dr-kishan-rao-k', 'doctors/f2703222-f5bf-4827-b54c-0743ff40bd26.webp', 'MBBS, DNB (Ortho), MS (Ortho), MNAMS, PBFHS', ' Consultant orthopaedic and Hand surgeon', '63912', 'Hulimavu', 13, 'Dr. Kishan Rao is a specialized Hand Surgeon with advanced training in orthopaedics and hand surgery. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore. He is a double postgraduate in Orthopaedics from the prestigious Christian Medical College, Vellore, and pursued his subspecialization at the Dr. Paul Brand Center for Hand Surgery.\nDr. Rao has also been deputed to train government Orthopaedic and Plastic Surgeons in Bhubaneswar, where he demonstrated various techniques for correction of leprosy paralytic deformities. He is committed to delivering the highest standards of care, actively participates in seminars and conferences, and has published and presented multiple academic papers.', 1, '2026-02-02 14:32:54', '2026-04-09 12:31:34'),
(48, NULL, 'Dr Manohar Babu', 'dr-manohar-babu', NULL, 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '61141', 'Hulimavu', NULL, NULL, 1, '2026-02-02 14:33:58', '2026-02-02 14:33:58'),
(49, NULL, 'Dr Amith Shetty P', 'dr-amith-shetty-p', 'doctors/49f63e63-6065-4777-a6e6-9f2af49d4102.webp', 'MBBS, MS - Orthopaedics', 'Consultant Trauma and Joint Replacement Surgeon', '86086', 'Hulimavu', 17, 'Dr. Amith Shetty  is an Orthopaedic Surgeon with specialized training in Hip and Knee Arthroplasty. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore. He completed his MBBS from K.S. Hegde Medical College, Mangalore, Karnataka, and his MS in Orthopaedics from JJM Medical College, Davangere, Karnataka. He also holds the SICOT Diploma (Orthopaedics) from the International Society of Orthopaedic Surgery and Traumatology.', 1, '2026-02-02 14:35:26', '2026-02-17 09:14:21'),
(50, NULL, 'Dr Raghavendra D Rao', 'dr-raghavendra-d-rao', 'doctors/618eff0f-b57e-46e6-b2d8-96f4c15b4407.webp', 'MBBS, MS - Orthopaedics', 'Consultant orthopaedic spine surgeon', '61474', 'Hulimavu', 30, 'Dr. Raghavendra M S is an Orthopaedist, Joint Replacement Surgeon, Arthroscopic Surgeon, and Traumatology Specialist with 20 years of experience in these fields. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore. Over the years, he has worked at several major hospitals in Bangalore, gaining extensive experience in advanced orthopaedic care.\n\nHe completed his MBBS with 6th Rank from Jagadguru Jayadeva Murugarajendra Medical College (JJMMC) in 1997, followed by MS in Orthopaedics from Kasturba Medical College, Manipal in 2001. He further pursued a Fellowship in Joint Replacement from Christian Medical College & Hospital, Vellore in 2004. He has also attended international conferences and hands-on workshops on joint replacement and arthroscopic surgeries in Germany and Bangkok, enhancing his expertise in advanced orthopaedic techniques.', 1, '2026-02-02 14:37:35', '2026-04-09 12:31:12'),
(51, NULL, 'Dr Sudhindra Dharmavaram', 'dr-sudhindra-dharmavaram', 'doctors/8f62b367-c19f-43f9-bfa7-c3d07cb22b2a.webp', 'MBBS, MS - Orthopaedics', 'Consultant Orthopaedics Surgeon', '80575', 'Hulimavu', 18, 'Dr. Sudhindra Dharmavaram is a specialist in Pain Medicine and Interventional Pain Management. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore. His expertise lies in comprehensive and multidimensional assessment of chronic pain and the execution of advanced interventional pain management techniques.', 1, '2026-02-02 14:38:44', '2026-05-21 10:29:31'),
(53, NULL, 'Dr Rakhi Sircar', 'dr-rakhi-sircar', 'doctors/6d4d0187-d57d-447e-a40e-ffb668e7dace.webp', 'MBBS, MS - Paediatrics', 'Consultant Paediatrician', '70253', 'Hulimavu', 33, 'Dr. Rakhi Sircar is a Pediatrician in Bangalore with 33 years of experience in this field. She is a Consultant at Nano Hospitals in Hulimavu, Bangalore. She completed her MBBS from Calcutta National Medical College in 1993, Diploma in Child Health (DCH) from Dr. B.C. Roy Memorial Hospital for Children, Kolkata in 2000, and DNB in Paediatrics from the National Board of Examination in 2003.', 2, '2026-02-02 14:41:38', '2026-02-17 07:37:07'),
(54, NULL, 'Dr Ramya K S', 'dr-ramya-k-s', 'doctors/65c18c10-d424-4709-a155-93f175bcdcc9.webp', 'MBBS, MS - Gynaecology', 'Consultant Gynecologist, Obstetrician and Laproscopic Surgeon', '88023', 'Both', 16, 'Dr. Ramya K S is a Gynecologist, Obstetrician, and Laparoscopic Surgeon in Bangalore with 16 years of experience in these fields. She is a Consultant at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. She completed her MBBS from Vijayanagara Institute of Medical Sciences (VIMS), Bellary in 2009, MS in Obstetrics & Gynaecology from St. John’s Medical College, Bangalore in 2014, and a Fellowship in Minimal Access Surgery from World Laparoscopy Hospital, Gurgaon (NCR), New Delhi in 2019.', 3, '2026-02-02 14:42:58', '2026-02-17 07:39:28'),
(56, NULL, 'Dr Shruthi G Naik', 'dr-shruthi-g-naik', NULL, 'MBBS, MS - Gynaecology', 'Consultant Gynaecologist', '123144', 'Hulimavu', NULL, NULL, 3, '2026-02-02 14:45:42', '2026-02-02 14:45:42'),
(57, NULL, 'Dr Suresh C H', 'dr-suresh-c-h', 'doctors/221fe52b-8b8b-4e98-9eef-03463773e5ed.webp', 'MBBS, MD - General Medicine', 'Consultant Physician & Diabetologist', '88022', 'Hulimavu', 16, 'Dr. Suresh C H is a Consultant in Internal Medicine and General Physician in Bangalore with 16 years of experience in these fields. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore. He completed his MBBS from Bangalore Medical College and Research Institute, Bangalore in 2010 and MD in General Medicine from The Tamil Nadu Dr. M.G.R. Medical University in 2014.', 4, '2026-02-02 14:49:24', '2026-02-17 07:44:21'),
(58, NULL, 'Dr Namitha Rao', 'dr-namitha-rao', 'doctors/904452ab-1aa1-4838-abdd-2d715e9fc772.webp', 'MBBS, MD - General Medicine', 'Consultant Physician', '109990', 'Hulimavu', 10, 'Dr. Namitha Rao is a Consultant in General Medicine and Internal Medicine in Bangalore with 10 years of experience in these fields. She practices at Nano Hospitals in Hulimavu, Bangalore. She completed her MBBS from M.V.J. Medical College and Research Hospital in 2015 and DNB in General Medicine from the National Board of Examination, India in 2018.', 4, '2026-02-02 14:50:28', '2026-02-17 07:47:54'),
(59, NULL, 'Dr Aparna Parvatikar', 'dr-aparna-parvatikar', 'doctors/d788cc97-d7ee-4cdd-a7c1-6b768c037c24.webp', 'MBBS, MD - General Medicine', 'Consultant Physician', '111160', 'Hulimavu', 7, 'Aparna Parvatikar is an expert and experienced General Physician doctor. Aparna Parvatikar specializes in General Physician. Currently, Aparna Parvatikar is practicing at Nano Hospitals | OPD Hulimavu, Bengaluru is fluent in english, and provides compassionate care for all the patients to ensure complete recovery. Aparna Parvatikar strives to provide advanced medical care in a comfortable and holistic environment for all patients coming for treatment.', 4, '2026-02-02 14:51:21', '2026-05-21 11:18:14'),
(60, NULL, 'Dr Pudukode Ramnath Krishnan', 'dr-pudukode-ramnath-krishnan', 'doctors/080d609a-0453-4b4a-8efb-eb0c2d672e93.webp', 'MBBS, DM - Neurology', 'Consultant Neurologist', '35974', 'Both', 33, 'Dr. P. R. Krishnan is an eminent Neurologist from Bangalore with a special interest in headache disorders. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore and Nano Hospital in Uttarahalli, Bangalore. He completed his MBBS in 1992 from Bangalore University and MD in Internal Medicine in 1997 from the prestigious Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER), Pondicherry. In 2002, he completed his DM in Neurology from the All India Institute of Medical Sciences (AIIMS), New Delhi, and also obtained DNB in Neurology from the National Board of Examinations, New Delhi.', 6, '2026-02-02 14:52:35', '2026-02-17 07:51:13'),
(62, NULL, 'Dr Richa Mishra', 'dr-richa-mishra', NULL, 'MBBS, MS - General Surgery', 'Consultant General Surgeon', '99874', NULL, 13, 'Dr. Richa Mishra is a General Surgeon in Bangalore with 13 years of experience in this field. She is a Consultant at Nano Hospitals in Hulimavu, Bangalore. She completed her MBBS from Sri Siddhartha Medical College, Tumkur in 2013 and DNB in General Surgery from the National Board of Examination in 2019.\n', 20, '2026-02-02 14:58:49', '2026-02-17 07:52:38'),
(63, NULL, 'Dr Agnigundala Anusha', 'dr-agnigundala-anusha', NULL, 'MBBS, MS - General Surgery', 'Consultant General Surgeon', '0002315', 'Hulimavu', 16, 'Dr. A. Anusha is a General Surgeon in Bangalore with 16 years of experience in this field. She is a Consultant at Nano Hospitals in Hulimavu, Bangalore. She completed her MBBS from NRI Medical College in 2010 and MS in General Surgery from NRI Medical College in 2016.\n', 20, '2026-02-02 14:59:57', '2026-02-17 07:54:45'),
(64, NULL, 'Dr Manish Pangi', 'dr-manish-pangi', NULL, 'MBBS, MS - Vascular Surgery', 'Consultant Vascular Surgeon', '63524', 'Hulimavu', NULL, NULL, 12, '2026-02-02 15:01:48', '2026-02-02 15:01:48'),
(66, NULL, 'Dr Hanumesh A', 'dr-hanumesh-a', NULL, 'MBBS, MS - ENT', 'Consultant ENT Surgeon', '132038', 'Hulimavu', NULL, NULL, 15, '2026-02-02 15:03:31', '2026-02-02 15:03:31'),
(67, NULL, 'Dr Spoorthi G Itigi', 'dr-spoorthi-g-itigi', NULL, 'MBBS, MS - ENT', 'Consultant ENT Surgeon', '105550', 'Hulimavu', NULL, NULL, 15, '2026-02-02 15:04:16', '2026-02-02 15:04:16'),
(68, NULL, 'Dr Ranjani Gunasheelan', 'dr-ranjani-gunasheelan', NULL, 'MBBS, MD - Dermatology', 'Consultant Dermatologist', 'KMC0000503', 'Hulimavu', NULL, NULL, 13, '2026-02-02 15:05:25', '2026-02-02 15:05:25'),
(70, NULL, 'Dr Neeraj', 'dr-neeraj', 'doctors/e49ca260-ab7f-4858-af39-498fd7429d91.webp', 'MBBS, MD - Psychiatry', 'Consultant Psychiatrist', '100855', 'Hulimavu', 9, 'Dr. Neeraj is a Consultant Psychiatrist with over eight years of experience across multispecialty corporate hospitals, tertiary care centres, and digital mental health platforms. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore. He specializes in Adult Psychiatry with focused clinical interests in mood disorders and addiction psychiatry.', 16, '2026-02-02 15:07:49', '2026-02-17 08:03:07'),
(72, NULL, 'Dr Nikitha', 'dr-nikitha', NULL, 'MBBS, MS - Plastic Surgery', 'Reconstructive Surgeon', '44595A', NULL, NULL, NULL, 18, '2026-02-02 15:10:00', '2026-02-02 15:10:00'),
(73, NULL, 'Dr Srinivas C', 'dr-srinivas-c', 'doctors/6cfa8802-cc55-47b2-aafb-7576bbc8efa3.webp', 'MBBS, MD - Rheumatology', 'Consultant Rheumatologist', '65685', 'Hulimavu', 23, 'Dr. Srinivasa Chennareddy is a DM-qualified Rheumatologist with expertise in the diagnosis and management of rheumatoid arthritis, ankylosing spondylitis, vasculitis, metabolic bone disorders, and osteoporosis. He is a Consultant at Nano Hospitals in Hulimavu, Bangalore, providing comprehensive rheumatologic care with a focus on evidence-based and patient-centered treatment approaches.', 17, '2026-02-02 15:11:05', '2026-05-21 12:29:45'),
(74, NULL, 'Dr A.S Sushrith Urs', 'dr-as-sushrith-urs', 'doctors/36ae2a4e-dab3-4abe-bbaf-a2d4cd28747c.webp', 'M.B.B.S, M.S General Surgery', ' General Surgeon ', '123348', 'Uttarahalli', 10, 'Dr. Sushrith URS is a General Surgeon in Bangalore with 10 years of overall experience, including 1 year as a specialist. His medical registration is verified. He is a Consultant at Nano Hospital in Uttarahalli, Bangalore and Nano Hospitals Uttarahalli in Chikkakallasandra, Bangalore. He completed his MBBS from Rajiv Gandhi University of Health Sciences in 2016 and MS in General Surgery from Dr. B. R. Ambedkar Medical College in 2023.', 20, '2026-02-03 06:38:40', '2026-05-21 13:00:54'),
(77, NULL, 'Dr. Sreedhara Murthy B N', 'dr-sreedhara-murthy-b-n', 'doctors/ffb79228-5527-4d2c-b6b5-7b05ba260e6d.webp', 'MBBS, MS - General Surgery, MCh - Pediatric Surgery', 'Consultant Paediatrician', '34836', 'Both', 33, 'Dr. B. N. Sreedhara Murthy is a highly experienced Paediatric Surgeon associated with Nano Hospitals, Uttarahalli and BG Road, Bengaluru, with over 33 years of overall medical experience, including 26 years of specialised expertise in paediatric surgery. He is known for his compassionate approach and advanced surgical care for infants, children, and adolescents across a wide range of paediatric conditions. Dr. Murthy has received several academic and non-academic recognitions throughout his career, including the prestigious President Award in Scouting presented by the Honourable President of India, Gyani Zail Singh, in 1984. He has also contributed extensively to the medical field through multiple publications and paper presentations in paediatric surgery', 2, '2026-05-08 06:08:09', '2026-05-08 06:28:37'),
(78, NULL, 'Dr. Krithika D Muralidhar', 'dr-krithika-d-muralidhar', 'doctors/36f29750-c62a-476c-a713-65c8fc2c051d.webp', 'MBBS, MD, MRCP (London),  DNB (Nephrology)', 'Consultant Nephrologist', '83201', 'Both', 11, 'Dr. KRITHIKA D. MURALIDHARA is a Doctor and has an experience of 11 years in this field. The doctor completed MBBS from Karnatak University in 2009', 26, '2026-05-12 09:48:47', '2026-05-12 09:48:47'),
(79, NULL, 'Dr Dhruva H M', 'dr-dhruva-h-m', 'doctors/32270292-df4f-4c4b-aa32-10725e150030.webp', 'MBBS,MS,DNB,MCh', 'Consultant Urologist', '117557', 'Both', 10, 'Dr. Dhruva H M is a Urologist in Uttarahalli, Bangalore and has an experience of 9 years in this field. Dr. Dhruva H M practices at Nano Hospital in Uttarahalli, Bangalore. He completed MBBS from Kempegowda institution of medical college in 2017,MS - General Surgery from kempegowda institution of medical science in 2021 and MCh - Urology from SHRI B M patel medical college vijayapura in 2025.', 8, '2026-05-12 09:53:25', '2026-05-12 09:55:17'),
(80, NULL, 'Dr kirthi kiran', 'dr-kirthi-kiran', 'doctors/e91f1303-3f9f-41c5-b623-9d53e0893653.webp', 'MBBS, MS', 'CONSULTANT ENT &HEAD NECK SURGEON', '112127', 'Hulimavu', 6, 'Dr. Kirthi Kiran is an experienced ENT Surgeon practicing at Nano Hospitals, BG Road branch, Hulimavu, Bengaluru. He specializes in the diagnosis and treatment of ear, nose, throat, head, and neck conditions using advanced medical and surgical techniques. Dr. Kirthi Kiran is known for providing patient-focused care with expertise in managing sinus disorders, throat infections, hearing problems, and ENT-related surgeries. He is committed to delivering comprehensive and effective treatment with a focus on long-term patient well-being.', 15, '2026-05-14 07:38:19', '2026-05-14 07:42:55'),
(81, NULL, 'Dr Sharan Achar T', 'dr-sharan-achar-t', 'doctors/c1538d8c-cad4-4d80-b0f4-6297b1941d9a.webp', 'MBBS, MS Ortho, DNB, FASSI, FAO', 'Consultant Orthopaedic Spine Surgeon', '109282', 'Both', 11, 'Dr. Sharan Achar T is an experienced Orthopedic Spine Surgeon practicing at Nano Hospitals. He specializes in the diagnosis and treatment of spine disorders, back pain, neck pain, slipped disc, spinal injuries, and degenerative spine conditions. Dr. Sharan Achar T completed his MBBS from Mysore Medical College and Research Institute in 2015, MS in Orthopaedics from The Tamil Nadu Dr. M.G.R. Medical University in 2019, and DNB in Orthopedics/Orthopedic Surgery from National Board of Examinations in 2019. He is known for providing patient-focused spine care using advanced orthopedic and minimally invasive treatment approaches.', 1, '2026-05-14 07:46:47', '2026-05-14 07:46:57');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `doctors`
--
ALTER TABLE `doctors`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `doctors_slug_unique` (`slug`),
  ADD KEY `doctors_speciality_id_foreign` (`speciality_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `doctors`
--
ALTER TABLE `doctors`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=82;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `doctors`
--
ALTER TABLE `doctors`
  ADD CONSTRAINT `doctors_speciality_id_foreign` FOREIGN KEY (`speciality_id`) REFERENCES `specialities` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
